### ISSUE TITLE
Q: Best way to separate logic, layout, and styles into different files in a Nue application?

### ISSUE THREAD

**Issue by globalpartnersoftdevelopment** [nuejs/nue#107]
How exactly we should separate logic, layout, and styles into different files in a Nue application?

The main task of the components of a large application is to make abstractions where appropriate and possible.

In my react projects, I've used the following separation of components:
1) Layout: modules/users/layouts/SignInForm/index.tsx
2) Styles: modules/users/layouts/SignInForm/styles.tsx
3) Logic: modules/users/hooks/useSignInForm.ts

What is the best way to properly split the logic, styles, and layout into three different files with "imports" of each other in Nue.js?

**Comment by tipiirai** [comment]
Please check out the announcement of Nuekit: 

https://nuejs.org/blog/nuekit-010/

Likely solves your issue.
