### ISSUE TITLE
Bun create error: Failed to run "create-nue" due to error InvalidExe

### ISSUE THREAD

**Issue by Dugnist** [nuejs/nue#110]
What version of Bun is running?
1.0.17

What platform is your computer?
MacBook Air, Chip: Apple M2, MacOS Ventura 13.4

What steps can reproduce the bug?

```
bun install nuekit --global

// bun add v1.0.17 (5e60861c)
// installed nuekit@0.1.3 with binaries:
//  - nue
// 1 package installed [11.00ms]

bun create nue@latest      
// error: Failed to run "create-nue" due to error InvalidExe
```

What is the expected behavior?
When I run "bun create nue@latest" -> I expect to start installing process.

What do you see instead?
When I run "bun create nue@latest" -> I see error instead

**Comment by tipiirai** [comment]
This is a known issue addressed on the documentation: https://nuejs.org/docs/#start-with-a-template

The recommended workaround is to use `pnpm`. I'm expecting Bun to fix this issue at some point. Need to post an issue for them.

**Comment by tipiirai** [comment]
This issue is now fixed. Try `bun create nue@latest`
