### ISSUE TITLE
Hot reloading doesn't always seem to work

### ISSUE THREAD

**Issue by adhawkins** [nuejs/nue#115]
If I create a simple site containing just an index.md page, then any pages made to this are reflected immediately in an open browser window.

However, if I add a layout.html, it appears that changes to this file are only applied when I refresh the browser page displaying the site.

index.md:

```
---
title: A test page
description: Me testing stuff
---

# Testing testing
```

layout.html:

```
<header>
	<h1>This is the header</h1>
</header>

<footer>
	<h2>This is the footer</h2>
</footer>
```

I'm running the nue binary in the directory containing these files. If I make an edit to `index.md` it shows up immediately. If I make an edit to `layout.html` it is only visible after refreshing the browser page.

Everything is running within a Docker container. I can provide the docker-compose and Dockerfile if they'd be of interest, but it's pretty basic.

**Comment by tipiirai** [comment]
Damn. Sounds like a challenging issue to hunt! I have no experience with Docker so I cannot set this up. Do you have any ideas on how I could repeat/see the issue?

**Comment by adhawkins** [comment]
I can provide you with the docker-compose.yaml file and Dockerfile to generate the container. You'd need access to (I think) a Linux machine to build the container on. Is this something you could do?

**Comment by adhawkins** [comment]
Oddly, I tried to get it ready so I could package everything up for you, and now it seems to be working! I don't *think* I've changed anything, but it's possible there was something wrong with the way the container was being built.

I'll close this for now. Apologies for the noise!

**Comment by tipiirai** [comment]
Good to hear!
