### ISSUE TITLE
Favicon issue

### ISSUE THREAD

**Issue by korabdoroci** [nuejs/nue#119]
When I follow the getting started guide and pick the skeleton app and run:

`~/Downloads/test/test$ nue`

I get:
`✓ Created symlink .dist/dev/@nue/page-router.js
✓ Created symlink .dist/dev/@nue/app-router.js
✓ Created symlink .dist/dev/@nue/hotreload.js
✓ Created symlink .dist/dev/@nue/mount.js
✓ Created symlink .dist/dev/@nue/diffdom.js
✓ Created symlink .dist/dev/@nue/error.css
✓ Added default /favicon.ico 

✓ Engine: Bun 1.0.18
✓ Serving site from ./.dist/dev
✓ Building site to: ./.dist/dev

✓ Processing styles 1
   style/global.css

✓ Transpiling components 2
   views.nue
   app.nue

✓ Single-page apps 1
   index.html

Time taken: 7ms

✓ http://localhost:8080/ `

And when i check my browser I get this error in the console:

`Firefox can’t establish a connection to the server at http://localhost:8080/. [hotreload.js:4:12](http://localhost:8080/@nue/hotreload.js)
GET
http://localhost:8080/favicon.ico
[HTTP/1.1 404 Not Found 0ms]`

For context I use Debian sid, Bun 1.0.18, Nue 0.1.3

**Comment by tipiirai** [comment]
Try now. Should work with the latest Nuekit version. You can upgrade with `bun install nuekit@0.1.7 --global`

**Comment by korabdoroci** [comment]
Thanks. You solved it!
