### ISSUE TITLE
create command Error

### ISSUE THREAD

**Issue by caesar1shi** [nuejs/nue#121]
/home/ubuntu/.npm/_npx/3f9020b1de426ac0/node_modules/.bin/create-nue: 1: import: not found
/home/ubuntu/.npm/_npx/3f9020b1de426ac0/node_modules/.bin/create-nue: 2: import: not found
/home/ubuntu/.npm/_npx/3f9020b1de426ac0/node_modules/.bin/create-nue: 4: import: not found
/home/ubuntu/.npm/_npx/3f9020b1de426ac0/node_modules/.bin/create-nue: 5: import: not found
/home/ubuntu/.npm/_npx/3f9020b1de426ac0/node_modules/.bin/create-nue: 7: Syntax error: "(" unexpected
npm ERR! code 2
npm ERR! path /home/ubuntu/code
npm ERR! command failed
npm ERR! command sh -c create-nue

npm create nue@latest command  execution error, environment: Ubuntu 22.04.2 LTS, node 21.2.0

**Comment by nobkd** [comment]
Have you tried using `pnpm create`?
For me, it also does not work with `npm create`

Also, this probably belongs here: https://github.com/nuejs/create-nue

**Comment by tipiirai** [comment]
`bun create@latest` now works
