### ISSUE TITLE
create error in wiindows11

### ISSUE THREAD

**Issue by caesar1shi** [nuejs/nue#122]
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

[Error: ENOENT: no such file or directory, lstat 'F:\F:\.pnpm-store\v3\tmp\dlx-25016\node_modules\.pnpm\create-nue@0.2.1\node_modules\create-nue\simple-crm'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'F:\\F:\\.pnpm-store\\v3\\tmp\\dlx-25016\\node_modules\\.pnpm\\create-nue@0.2.1\\node_modules\\create-nue\\simple-crm'
}

pnpm create nue@latest command error, environment: windows11, Node.js v20.10.0

**Comment by tipiirai** [comment]
Nue is currently developed under Mac only so Windows support is so-and-so. However, there will be a new version tomorrow that _might_ fix this issue. Fingers crossed.

**Comment by tipiirai** [comment]
Please try with the latest nuekit (v0.1.7)

**Comment by ShiMeiWo** [comment]
@tipiirai I tried nuekit on windows 10 and got the following error:

```sh
$ node $(which nue) --version
C:\Users\ShiMeiWo\AppData\Local\pnpm\nue:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.10.0
```

The runtime environment is:.

node: v20.10.0
pnpm: 8.12.1
nuekit: v0.1.7

Please take a moment to check it out. Thx!

**Comment by alexnguyennz** [comment]
> @tipiirai I tried nuekit on windows 10 and got the following error:
> 
> ```shell
> $ node $(which nue) --version
> C:\Users\ShiMeiWo\AppData\Local\pnpm\nue:2
> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
>           ^^^^^^^
> 
> SyntaxError: missing ) after argument list
>     at internalCompileFunction (node:internal/vm:77:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1288:20)
>     at Module._compile (node:internal/modules/cjs/loader:1340:27)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
>     at Module.load (node:internal/modules/cjs/loader:1207:32)
>     at Module._load (node:internal/modules/cjs/loader:1023:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
>     at node:internal/main/run_main_module:28:49
> 
> Node.js v20.10.0
> ```
> 
> The runtime environment is:.
> 
> node: v20.10.0 pnpm: 8.12.1 nuekit: v0.1.7
> 
> Please take a moment to check it out. Thx!

The script that's trying to run there won't work on Windows - I have this issue as well. It would probably be easier to use [Bun with WSL](https://bun.sh/docs/installation) for now.

**Comment by dexslender** [comment]
Same issue with `yarn create` & windows 11
![image](https://github.com/nuejs/nue/assets/91853649/438718e7-6ed0-4458-a3b9-ab274768b04e)

**Comment by dexslender** [comment]
@alexnguyennz I add nuekit in my project then `yarn nue` and work. Win11 (globally not work for me too :( )
![image](https://github.com/nuejs/nue/assets/91853649/67e6b94d-5932-4629-8033-8b268201b3bb)

**Comment by fritx** [comment]
> ```sh
> $ node $(which nue) --version
> C:\Users\ShiMeiWo\AppData\Local\pnpm\nue:2
> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
>           ^^^^^^^
> 
> SyntaxError: missing ) after argument list
> ```

To fix the pnpm shell error, personally `npm install -g nuekit` is recommended.

```sh
npm install -g nuekit
node $(which nue)
```

ref: [Contributing Guide - Linking](https://github.com/nuejs/nue/blob/master/CONTRIBUTING.md#linking), [Ci Testing](https://github.com/nuejs/nue/blob/master/.github/workflows/test.yaml#L37-L40) and https://github.com/nuejs/nue/pull/155
@ShiMeiWo @alexnguyennz

**Comment by appurist** [comment]
I'm seeing the same error, with freshly installed bun and nuekit on Windows 11. In my case, it looks like there's a leading backslash on the path before the drive letter. It doesn't seem to matter what template I choose.

```
> bun create nue@latest test2

T   create-nue
o  Your project directory name:
|  test3
o  Pick a template
|  Simple app
ENOENT: No such file or directory
   errno: -2
 syscall: "copyfile"
   path: "\C:\Users\paul\AppData\Local\Temp\bunx-208408912-create-nue@latest\node_modules\create-nue\simple-app"
x  Canceled
>
```

**Comment by nobkd** [comment]
Path issues on windows should be fixed (at least in nuekit), and there's a new `create` command in nuekit (with currently just `simple-blog` template).
I'll close this, as `create-nue` package will probably not really be updated.

Feel free to comment, if there are still Windows path issues.

**Comment by nobkd** [comment]
Path issues on windows should be fixed (at least in nuekit), and there's a new `create` command in nuekit (with currently just `simple-blog` template).
I'll close this, as `create-nue` package will probably not really be updated.

Feel free to comment, if there are still Windows path issues.
