### ISSUE TITLE
Using nue without NodeJS

### ISSUE THREAD

**Issue by bubnenkoff** [nuejs/nue#124]
Hello! I am looking for a tiny framework that can be used without NodeJS. Is it possible with Nue?

**Comment by tipiirai** [comment]
Technically yes, because Nue's primary engine is Bun. However, I expect that you meant to ask whether Nue components would work directly on the browser without the compilation step. This is a common request, but I don't see this coming to Nue anytime soon — if ever. See: https://github.com/nuejs/nue/issues/85

**Comment by bubnenkoff** [comment]
Thanks! But where to read how to `compile` site? I would like to serve it with static http server (not js-based -- caddy)

**Comment by tipiirai** [comment]
Here's how you get started with Nue: https://nuejs.org/docs/

Nue is a static website generator so you don't really have to worry about compilation. Just hit save on your files and watch the site auto-update on the browser.

**Comment by bubnenkoff** [comment]
Yes, but it's work in dev-time, but how to compile result as pages that can be served with static http file server?

**Comment by seneca** [comment]
nue serve --production

You can now push the production version at .dist/prod to some public server. You currently need to do this manually before the official deployment tool and Nue Cloud is available.

**Comment by bubnenkoff** [comment]
I am not from js-world, am I right understand that it's not possible with vue and react that would not work without nodejs on server?

**Comment by tipiirai** [comment]
Yes. Both Vue and React need a thing called "builder" on the server side. Popular ones are esbuild, vite, parcel, and turbopack.

**Comment by bubnenkoff** [comment]
Could you add more info to faq/docs from it. Not all people use js often. I still doing some sites with js time to time with alpinejs, but I want to have more flexible components and do not want to want to use nodejs on server

**Comment by tipiirai** [comment]
Sure.  I guess you are looking for documentation for beginners. What kind of info would be important?

**Comment by bubnenkoff** [comment]
@tipiirai I reread docs. Yes, I have found some answers. But I have new question. I had left web-dev (for tiny project use AlpineJS) because I faced with npm-hell (and did not want to serve sites with node).

Does neu solve this problem? I still afraid to get back to time when simple site for setup required hundreds of megabit of dependencies. Or it it a system problem and if I want to make site lightweight I should not use any dependencies?

**Comment by tipiirai** [comment]
@bubnenkoff Nue has 10-100x less dependencies than the mainstream options so in that sense the NPM "hell" issue is solved. Pretty sure you cannot find a more lightweight option out there. 

Also. With the latest release of [Nuemark](https://nuejs.org/blog/introducing-nuemark/) you have a pretty powerful and minimalistic content management system in place.
