### ISSUE TITLE
How to Fetch() on mounted()/construct() ?

### ISSUE THREAD

**Issue by noxomix** [nuejs/nue#129]
Im new to nue, and struggeling a bit with the fetching of JSON (API, ...) in the SPA example the fetching is done via the 
```js
router.on(async () => ...)
```
,but what if i dont want to use this router and just want to fetch some resource right in the component (Island) before the rendering of the component?

Currently Im doing it like so:
```html
<div :for="article in articles"> 
   { article.name }
</div>
<script>
constructor() {
    fetch("articles.json")
     .then(response => response.json())
     .then(data => {
           this.articles = data.articles
           this.update()
      })
      .catch(error => console.error(error));
}
</script>
```
Thats the only way I figured it out working - or is there another way how it should be done in Nue ? :)

Best Regards

**Comment by tipiirai** [comment]
You cannot indeed have async constructors so you must resort to promises making the code slightly harder to follow. I think the cleaner way to do it is to load the resources outside the component and then mount the component with the fetched data. Something similar that you find on the [Build a simple SPA](https://nuejs.org/docs/tutorials/build-a-simple-spa.html#create-a-controller) tutorial. Look for `this.mountChild` method. 

Does that work for you?

**Comment by noxomix** [comment]
Thank you, actually I thought it would be more like abstract / lightweight if i could do it in the component directly , Because this makes it more complex for me. 

Indeed i think in practice at bigger applictions there will be a helper script which provides you the communication to the API and every Island can take use of it.

But it would be nice to have an abstract/direct way where only one Island is part of it and you just need to look in the Island and see "ah this Island load the data from there, and do things here [...]". And since nue lazy loads components i thought there would be a direct way, i mean i could create a while Loop in the constructor which only returns When a variable changes but i dont think thats exactly a good idea ^^

But okay then i will look into the other way. Thanks.

**Comment by tipiirai** [comment]
You certainly have a point there. The alternative is to do this exactly the way you presented on the constructor. Or maybe put your code inside `async mounted()` callback so you can use `await` making the code more readable and compact.

**Comment by noxomix** [comment]
Great! Knowing that i can make an async mounted() now its way better.

But I still need the this.update() so for a millisecond the placeholder "nodata found" data displayed in my table. Which means the Island loads itself then loads the data and then updates itself.

What about implementing a `async before()` besides mounted(), construct(), updated() etc which didnt render the component before the async function finishes? Or will this break any lifecycles and routines/concept of nue? Or an optional async constructor() maybe.

Independent Islands vs Islands dependent on mainland ;)

Best Regards

EDIT:
I looked a bit into the `/browser/nue.js` and tried some things to understand the code. After understanding it partialy, im pretty sure that for implementing such thing the whole mount(wrap) and the calling createApp() need to be async which will restructure Everything so maybe not a good idea.

Instead it would be good if we can optionally initialize a component but not render/mount it in the DOM. And then explicit call the `e.g. display()?` function at the End of the `async mounted()`, -> We initialize/mount the component without displaying it -> then we async fetching in the mounted() -> then we display it for the first time. But as im writing this i realised , its quite simple just put a :if on the root-element of the component will exactly do this 😅. OK thats my final thoughts on this.
