### ISSUE TITLE
Front-matter logic strips content when using `---` divider

### ISSUE THREAD

**Issue by nobkd** [nuejs/nue#138]
https://github.com/nuejs/nue/blob/854f20f53aecd8f32d87860b760cd24b8f1a3209/packages/nuekit/src/util.js#L10

The line above results in cut content when using `---` (`<hr>`) dividers in your Markdown other than front-matter ones.

I fixed it locally by replacing the line with the following code:

```js
let [_, front, ...md] = raw.split(/---+\n/)
md = md.join('---\n')
```

But I think, this'll cause problems later on, as it still does not allow Markdown files to have no front-matter at all when using dividers!

I currently can't think of a way to fix it myself, so someone else might be interested.

**Comment by tipiirai** [comment]
The logic of parsing front matter will change on the Nuemark release. Currently looking [like this](https://github.com/nuejs/nue/blob/nuemark/packages/nuemark/src/parse.js)

**Comment by nobkd** [comment]
Good to hear that! I read / skimmed over it, and this looks great so far.

Should this issue be kept open for tracking, or is it better to close this?

---

Just read over the file some more, and thought of some shorter `createHeaderId`:

https://github.com/nuejs/nue/blob/dddb9f5b72bb11becdb192fb5cb67b81237df7ea/packages/nuemark/src/parse.js#L60-L65

you could minify `replace(/\W/g, '-').replace(/-+/g, '-')` to one expression
also `if ... if` can be replaced with one regex replacement

```diff
-  let hash = text.replace(/\W/g, '-').replace(/-+/g, '-').toLowerCase()
-  if (hash[0] == '-') hash = hash.slice(1)
-  if (hash.endsWith('-')) hash = hash.slice(0, -1)
-  return hash
+  return hash = text.replace(/[\W_]+/g, '-').replace(/^-*(.*?)-*$/, '$1').toLowerCase()
```

But maybe the second regex is too hard to read.

Edit: added `_` to be also replaced, as it is bad practice for URLs
Edit 2: if the string contains no `A-z` chars, it'll end up as empty-string. this can happen quite often, if someone is e.g. using only... idk... Chinese characters. But I also don't have an alternative in mind

**Comment by nobkd** [comment]
The purpose of this issue is gone, as no content is lost anymore.

The only thing I think might be problematic with the new `---`-handling is, that the behavior differs from Markdown's original behavior.
Sometimes, you really just want to have a `<hr>` divider and don't split your content to [sections](https://nuejs.org/docs/reference/nuemark-api.html#sections).

What are your thoughts about that, and regarding the repurposing of the `---` separator?

**Comment by tipiirai** [comment]
I think `---` makes a good separator character because it already acts as one in the front matter. 

You can render horizontal lines with `___`, `***` or `- - -`.

Added a section about [horizontal lines](https://nuejs.org/docs/concepts/nuemark.html#horizontal-lines) to the docs. 

Thanks!

**Comment by nobkd** [comment]
Thanks :+1:
