### ISSUE TITLE
Should all links of activated routes be set to the selected state?

### ISSUE THREAD

**Issue by caesar1shi** [nuejs/nue#158]
![image](https://github.com/nuejs/nue/assets/16809701/d1ed0032-8217-4184-a870-f1f8951e9113)

**Comment by tipiirai** [comment]
Is this the www repository?

**Comment by tipiirai** [comment]
This is some old code I don't seem to find anywhere on the current repositories. Please help!

**Comment by tipiirai** [comment]
OOPS. Found this from page-router. Not sure why I could not find this with my text editor search. Fixing!

**Comment by tipiirai** [comment]
Now fixed. Thank you and sorry for the noise!
