### ISSUE TITLE
zsh: command not found: nue

### ISSUE THREAD

**Issue by happy15** [nuejs/nue#160]
Hi there, 

just followed steps on https://nuejs.org/docs/, but failed when running "nue".

anything do I miss?

my env is:
- macOS Sonoma 14.2.1 on mbp 14.
- bun 1.0.22

**Comment by Darth-Ness** [comment]
Try running `bunx nuekit`. That did the trick on my machine.

**Comment by happy15** [comment]
> Try running `bunx nuekit`. That did the trick on my machine.

Thanks, `bun x nuekit` works.

**Comment by garronej** [comment]
`~/.bun/bin` needs to be added to the `PATH`
