### ISSUE TITLE
executing nue with node

### ISSUE THREAD

**Issue by weagle08** [nuejs/nue#173]
Ubuntu 22.04
Node 20.10

Installed nuejs with `npm install nuekit -g`. Running `node $(which nue) --version only prints the version of nodejs`. Would like to evaluate Nue for use on a company project and bun is a no go.  Have verified that nue is installed in the npm modules directory and symlink was created in the node/bin directory. When executing `./nue` i get this error: `/usr/bin/env: ‘bun’: No such file or directory`. How do I change Nue's run target?

**Comment by Darth-Ness** [comment]
It should just run....  I wonder if `npm x nuekit` would work?

**Comment by weagle08** [comment]
I got it running. Was my mistake, had to create symlink to a directory on my path (/usr/local/bin). However it doesn't seem to want to work with node or the initial [Create a SPA landing page](https://nuejs.org/docs/tutorials/build-a-simple-spa.html#create-a-spa-landing-page) is missing some steps such as a package.json with install for node.

```
✓ Nue 0.3.1 • Node 20.10.0 
✓ Serving site from ./.dist/dev
✓ http://localhost:8080/ 
✓ index.html 
Not found /@nue/hotreload.js
node:_http_server:345
    throw new ERR_HTTP_HEADERS_SENT('write');
          ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at Server.<anonymous> (file:///opt/node-v20/lib/node_modules/nuekit/src/nueserver.js:57:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v20.10.0
```

 Whatever the case I like the syntax, but without node being a first class supported runtime I don't know that this project will get enough adoption to be long lived. Hopefully I'm wrong because I'd love a contender to React, but requiring a new runtime to be installed to just build a front end client I don't think will go over too well.
