### ISSUE TITLE
I dont think nested tabs work, or if it does, example documentation is needed 

### ISSUE THREAD

**Issue by goblinfactory** [nuejs/nue#176]
I've created a spike (example) of nested tabs here
https://blog.alanhemmings.com/posts/taking-nuejs-for-a-spin-early-thoughts#tab-3

<img width="678" alt="Screenshot 2024-01-22 at 10 25 44" src="https://github.com/nuejs/nue/assets/1073487/8ec3bf2f-82f4-456b-a9d9-0c99d04a1317">

The problems are;

1. Only the first nested tab's content appears when clicked
2. First nested tab's content should be visible by default
3. None of the other tabs (of a nested tab) show their contents when clicked.
4. No documentation explain how to actually use tabs; what you need to do yourself to get tabs working. Nested or otherwise. i.e. no documentation for how to use standard tabs. I had to work it out by looking at generated html and auto included javascript.
5. The numbering of the sub-tabs appears to overlap with the parent tabs.

**Comment by tipiirai** [comment]
Wow. Thank you for the detailed feedback on that web page! This is great. I'll go through the issues and update things accordingly. I can totally see nested tabs being broken. Didn't try that at on the first version. Need to fix / add tests.
