### ISSUE TITLE
Nue didn't build static files on Windows using esbuild

### ISSUE THREAD

**Issue by brynne8** [nuejs/nue#179]
The JS files are successfully built, while static html file not generated.

```
D:\git_work\simple-crm>nue build
✓ Initialize ./.dist/dev
   nuemark.js
   nue.js
   page-router.js
   app-router.js
   mount.js
   diffdom.js
   hotreload.js
   error.css
   favicon.ico

✓ Nue 0.3.2 • Node 18.19.0
✓ Building site to: ./.dist/dev

Time taken: 7ms
```

**Comment by tipiirai** [comment]
How is the `nue` command using Node by default? Have you possibly edited the shebang?

**Comment by brynne8** [comment]
> How is the `nue` command using Node by default? Have you possibly edited the shebang?

Yes. I edited the shebang. Since windows don't know `which`.

**Comment by tipiirai** [comment]
Gotcha. Really hard for me to debug this issue without a Windows machine. Hope someone else can jump in.
