### ISSUE TITLE
Inline components

### ISSUE THREAD

**Issue by nobkd** [nuejs/nue#187]
Is there a way to use components inline with `[]`-syntax in Markdown?

Like

```md
# Title

text [component-name] stuff...

More text [.class-name] etc.

[clock] 00:00 - some time

```

**Comment by tipiirai** [comment]
Currently no, but would make sense. This requires an understanding of Marked internals. [This thread](https://github.com/markedjs/marked/issues/2125) may offer a solution.

**Comment by nobkd** [comment]
Should be supported on `dev` branch

**Comment by goblinfactory** [comment]
**Was this closed in error?** 

I've just tried creating a custom component, and I've tried simply using inline `<span>`s. 
So the simplest requirement of custom formatting a single word in a sentence is currently NOT possible.

For example,
```markdown
# Some heading

Here is a sentence with the name of the car in red. I drive a <span class='red'>Ford</span> to work. 
```

Using the latest version of Nue the above is still not possible to do using markdown in Nue. 
Maybe I've missed something?  I also was unable to do any of kind of any inline formatting even using a custom component.

**Comment by nobkd** [comment]
@goblinfactory 

This issue was to allow inline nuemark tags from custom html tags.

Nuemark doesn't support html tags (currently), but with  #470 you then would be able to at least do the following: `I drive a [.red "Ford"] to work.`

Currently also trying to implement a fallback to simple html rendering, if the component name is not registered as custom, and is a standard html element. (for both block and inline)
