### ISSUE TITLE
Is there any guide to add page transitions?

### ISSUE THREAD

**Issue by ArnavK-09** [nuejs/nue#203]
## Like astro's ` <ViewTransition /> `

Like astro`s ` <ViewTransition /> `

> ^ man idk how it happened tag got totally removed here

![Screenshot_2024-02-15-12-34-30-45_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/nuejs/nue/assets/69188140/90bd7953-7bca-486c-94e7-f80182b8efe7)

**Comment by tipiirai** [comment]
Not yet. However, page transitions will be a core part of the system. They are so important piece of the end-user experience.  Focusing on this one after the [design system](189) and templates. Thanks!

**Comment by tipiirai** [comment]
There is now. It's very simple and standards based. Two examples:

https://sofa-company.nuejs.org/
https://aimee-app.nuejs.org/

Just a few lines of CSS can do it: 

https://github.com/nuejs/create-nue/blob/master/sofa-company/global/sofa-company-design.css#L69-L72

**Comment by nobkd** [comment]
https://caniuse.com/mdn-css_selectors_view-transition-old

Only works for chromium based browsers. The view transition api is not (yet) implemented for Safari and Firefox.

**Comment by ArnavK-09** [comment]
Thanks both 📈📈
