### ISSUE TITLE
Error whule creating on Windows

### ISSUE THREAD

**Issue by RayyanNafees** [nuejs/nue#208]
I ran `bun create nue@latest` and was greeted with this error:

```pwsh
63 | ${e.green(S)}  ${e.reset(n)} ${e.gray(B.repeat(Math.max(s-t-1,1))+Z)}
64 | ${c}
65 | ${e.gray(z+B.repeat(s+2)+X)}
66 | `)},ue=(r="")=>{process.stdout.write(`${e.gray(d)}  ${e.red(r)}
67 |
68 | `)},oe=(r="")=>{process.stdout.write(`${e.gray(K)}  ${r}
                     ^
TypeError: Failed to create UVStreamSink: uv_pipe_open(1) src.windows_c.E.ISDIR
 code: "ERR_INVALID_ARG_TYPE"

      at node:stream:155:85
      at NativeWritablePrototypeWrite (node:stream:3706:141)
      at oe (C:\Users\nafee\AppData\Local\Temp\create-nue@latest--bunx\node_modules\@clack\prompts\dist\index.mjs:68:17)
      at C:\Users\nafee\AppData\Local\Temp\create-nue@latest--bunx\node_modules\create-nue\cli.js:23:1
```

![image](https://github.com/nuejs/nue/assets/59685062/82cb5dca-f78f-47b3-8031-f4182e13c873)

**Comment by RayyanNafees** [comment]
Upon checking `nue --version` the following error occured

```pwsh

61 |     dot()
62 |   }
63 |
64 |
65 |   // lets do it
66 |   process.stdout.write(colors.green('✓') + ` Initialize ${dist}: `)
       ^
TypeError: Failed to create UVStreamSink: uv_pipe_open(1) src.windows_c.E.ISDIR
 code: "ERR_INVALID_ARG_TYPE"

      at node:stream:155:85
      at NativeWritablePrototypeWrite (node:stream:3706:141)
      at C:\Users\nafee\.bun\install\global\node_modules\nuekit\src\init.js:66:3
```
![image](https://github.com/nuejs/nue/assets/59685062/a88d8d09-e49e-49d5-a1e2-46acc0378f2a)

**Comment by nobkd** [comment]
I'm pretty sure, that that is a `Bun for Windows` problem.

I've checked it on Linux and Windows, and the issue only occurs on Windows.
You can try using Bun with WSL for now, or use another package manager instead (and edit the [shebang to node](https://github.com/nuejs/nue/blob/master/packages/nuekit/src/cli.js#L1)), or wait for https://github.com/oven-sh/bun/issues/43 (takes its time)

(I think this issue might be specifically related to https://github.com/oven-sh/bun/pull/8456, but I'm not sure :shrug:)

Related issues: #122 and #179
