### ISSUE TITLE
nue-glow CSS width issue

### ISSUE THREAD

**Issue by gapmiss** [nuejs/nue#209]
When combining `numbered` and either `diff` or `highlight` features, the  highlighted code block lines extend beyond their width.

![CleanShot-Obsidian-Livecodes  GLOW from NUEjs - Playground - Obsidian v1 5 6-2024-02-18-09 39 28](https://github.com/nuejs/nue/assets/98914514/e4e2f695-d3e5-44b6-bf53-063dbe8bdb81)

**Comment by nobkd** [comment]
The `width: 100%` on `dfn`, `ins`, `del` somehow clash with the `::before` of the wrapping `span`s for the line numbers...
It looks, as if the width of the `::before` is not counted towards the width of the whole wrapping `span` for whatever reason. 🤷 

I'm not sure how to fix this...

---

A not optimal way could be to `calc(100% - "::before's-width")` on the `dfn`, `ins`, `del` (could break on overflowing/long lines?). But I wouldn't recommend that in any way.

**Comment by nobkd** [comment]
This one might be related: https://github.com/nuejs/nue/discussions/197#discussioncomment-8475296

**Comment by tipiirai** [comment]
Try setting the [--glow-padding](https://nuejs.org/docs/concepts/syntax-highlighting.html#css-variable-reference) variable. For example:

``` CSS
[glow] {
  --glow-padding: 2em;
  padding: var(--glow-padding);
}
```

**Comment by gapmiss** [comment]
@tipiirai Your suggestion had no effect. You can see the code here:

https://v24.livecodes.io/?x=id/vyz62pnwiq7

Thanks!

**Comment by tipiirai** [comment]
[Fixed it](https://v24.livecodes.io/?x=code/N4IgLglmA2CmIC4QHEAyB5A6gAgGYCcB7AW2wDkBVAUQCsBnEAGhABNY6BjfCAB0kIB2iEExAALWAEMWwgDzFYYSdg5jJ+OooC8AHRAUAKgDEAtAA492APQA+HQPmLlAyQt0gAbhFgB3HoXwwSw5BMFgBMHcfCBYwMS02Lw5YE2jYsUZsCAEoCEloE0582C0ARgA6AAZLW1ExMGJoAEEwMA1haEkBAHN3cODOujp3FnUAaz1RJW6GBABtAF1mSQ5ID1gqFigA4TowAE84UWJxgFceRFBOntPJbvgkesbREIjwsDkAQhMTbHqwHh0BBWKwCU6wejlALdKwsQgcOhWV7JPiIuj7CKSAAeJjEEG6Ymg+Pq2W65Se0GwPzsDm+v3+gOBVm6UDEpwARuUQsRQeD6LzYFY2rBBSc9rB8FYeCsxnd2MzoIQfFSTDT7LIxAAmGwACQMAFlULIrFqabIth4six3BTLN1FT4adhsLIePhYDZjW6PerYRAPGqHKaAMIAZVDxtN6otVvcCLododTpd3s9UvdZr9Afs6tNAClJB5JJxuHxI9ro-7Y3oaIXi1xeEEQNh7Urk66M16M76LYGNfhsHtDiU9Cd8CyBCZ2YqOGNCkpAghsJrYMQANzYMcTqczufhFhLgDMq7XNT7YkPNjDoewRe4kmnsGw7twEvCyUjl5zDh4NlQED2bBCFwbB8kpa9b3UPJH2wFwFDoUCBBYbA4ifYs6HhPI1ifPVDWwWA4AUCI6C9PslBgjhBmGPRWx8EwQkVDQ9HbVDpGTZ1ZDadjnRdOIr3DSD70fY0+PsHieM4sQbAAEVgXBJFOaAwEg6BwREqSxPE3ipNw1AULudTuI4vjZJLRsIEEQzNI4oV8HbIUJDYzTOPZQgWH2bjOLs6yJLAFgbBWZIInowhGJE-yfOM-yAGIABZSgATlwZLwqM3j-L2IgelSyL0psOgeFgDg8kpVceDUOgAJygRxJE7yat8+qtLy9lixSBiAmq5rOJigBWfquq0nq0z8tLhtwAJYG6IhTiQlRQs6oUIoamyuJ8ryxtG1R1BCsKls2mKADZYoAdlisx2UG2rRogK7fP89l8BlRQ6EybkxXKT67rqzy1pW+6bHe95dsW0bcuGuLYF6lhDtKO6ovy854byoHiO+2zfqaoatsIWawnwEH8GRiHTv6w6EuJ0bKf8okBCfMFiHZCUSP29aMfWv7utGtgCg6onWf+hHNV6ypMlKUpRewUpD0qambB5uWecUWBkNp9h0c5xqDpsCUiAJvm5ei5LZYFrn-NOOXdcm3GEJ8AIWBZsH-p+jmseu-zsjoQm5ZFzJNQlsWEpNp2zZsT25c9iUwlV7J1dNiT2edzX3ZsNXvfjlPfalsxJeF4PltDlhcAcDOAbxAkiQJaPsDVx2C4T5PeLdgG08IaVioOOXKnKUperluXy8JfFq7VoD26gfYNebjbwdG6UWC2bLS4R0pV375eUdCSRY4HefF+6KfMe1t0IDHfZ05D7GYpOhfD1wDg5cujfhpPs-QI4ILlIN0uXaT5uEc0K8UY+Bz7f0vinI2p1NTskOpbYgctAGCGAfsd+n95p7XAS6RO11-55U0HAVYKsL71wgZqBesV2S4E1LA5+o0xxjDlvQlW802CH1dtrAqRUSrEO1kbFKtCaYPgIggwqxV8jYDtvgB2KFCCDiUHNXGYA2ENREq5dymZyJwBpCAAAvswIcRwEBXC6N0W49xhDxheKEd4wgABUmRbEICZhNd0DiECSFwPjbAwBNKuRxJVAAXqSJcrkpESinIQLEp4BA6PsAgIghBlI+IanzQoqhVywCXMAsYNdiRgGibEgQ8TCCJO8ZpH4JxsgmAlpUJcRtKi4CSrgaJzoKnb0nJqSotTsDRVgA0zUr4WkqkqZOWKXS6k3xYHfDgQy2nZDqV0jgAzmnlJMCMkwItunRS6QlQ8RdZlrPaSYQ64yemVE1GYWKHAToHPWTnLZlQTq9QSmYXqBzpqSHPiLOpuAzDyXvu8p658ak-NKLgXqjTAWfJMJ0rZsAVx-MqFC8+MstkcHZCwXqsBSjIpMGMrZCVYqSEPOyMwyK6nHTOhdXFJytmk16uTXFJ1TnRUPIeeK-VcX3LqavTUuz2S4qDg83ApQTqakkAc90B4em4FinfLFBz9gEQdD82KyUEoStWTwbIYwfnsi6fCg5AQTGZJleyBKmpDwzNWdNEURSelErYDnA505wR1KtWYAZh0ClxISUk1ZdAuhe00NwXAS4TCSB4DwOAhR9jimIJkAAQrTMY+oVihjjWEYgRhQiZEDZOAgXRiqcEIJkJo6wcgDjILALEYBGA+VDFNQgT4KAAElMgACVCCuTAKW8giTZGhiDZkHUBF1iQA4Moat4IDkhogGG7AralRdGwOgaAyFQwHDgGWqNcBsDIHUK4JBSbixjAlF4aA27sAGFPuwcgvhsBdpOAIW5ghCAFRWCrJc+pwiKh9QINRKDkmtJ8LAdkYwoAmAmsFOgxASlxGCYhSA+Q8iaBYEM6DYAoOuAgNAfYS47wAAofj5uDRKedABKIZacJB5KXBUN5mk+YEfUMRkwHzz7MsqFRzSW55lS3KFi9c9hCliFKPWgQWoJMXmk7FMpDVCDrHwLgB0qQno8BCe6SQc5JHoc0jR2AdGBO9yGcxs5XShl8cnD23txAlzd2PMJmJ9gxPyedAZozFRKiMYaph1Ihmq5LiFdRxQ+NCjjx6OG7upR3ROedH5wJprJ3QA4IRzU5QVykAANTLg8D4HjDUrMRNaCQez5RYqxf-dOeEYwACOpxEmwAk7gfEpxXH2B4BJxSEnQpuc3OobcNnSsCcy-+hAgwsOqFw8hYD-XxxVKG3Z7ASKRP2HKNkvrrVZzTVxkhQmLH8BsY4+YLpBXnRmaIz8Y7sKzsqmO0Kg7R2gUbO47i75gknvQqFQVwp63xh-HE2tjbUmgf-Zk6D-AOTOsQ5yXECTf3IcoRm0xha+AfnJX-QjnJ5R2TKlmy1pSEolzZCU2AQjpQfsw+wOyU4JWikTQ4KcBCs3FFpwu6xq7z2bv-pc5qPrfn5LEFw-h7AehG3dGbdgNtehMgGEkGIEgkhMjIHCLAIsmQABqEpRguDzUGwo5GVnOYEPYOYtEFh9au6pveiHRso8Yo9q3SopxtUJpkaKkhxUPgp6Z3bYX3SaDAEuNnfuJTLaGTbyLUtVwfad3RSP3RbsC5w3hpccGBDvvbrAajsdcQBfqPR8oNzfH2yJ1LHgWJByhRiLH9jz2uOU4EGbh0FvbH89CP5oz+KMMd4Maa7IEhuD5M0mEWtJg2AhCevwe1A-yPD+N83pUFv2R9fZ4duPJhX7qFAaj93kzpmN8Xz4C3MfZtr6O6pxBSFt9u5lVAmBh-zdyKyt0VfqPHfsdU4FYGfN3fxSabgI-i3lkG-g7rXrRPRGoPrLvj0pSudOyEAUvtgKcH1qPlhhPsatPkuLNGwPgKPD4IWCgpdp-s7lbNAYxJkFKrdmgSYDgRKK3MlIHmVkJkMjQRgVPhZJOAhrOHTEMGVr3CeKtk3k-nQOcKAQEB-hAajJNjAdFIdLgCdJIDfEnr3hAAEv3pJnPkMqThAMlhGpXDPpoUPj3jBluv3koESNagvk-p0EzJSGfu-uAZfqItwr-jKslCocFKBkZlxv+kfhbvQptjKDtjgftk4c7kwiwLftFGQiwBQlQodLdmZrNIHkMqErgSYE9FsEzmVnboVgNvxiYA5jHkUeVoIQ1AnmVo5stmUU5oUv4YONKDVA4XjOEtkFwBkhEMHrniEK0QODikIQ0R+kUs4pNOIWjuEXRL0W8OQQEH-k8gyglEkdYl0fNH0YRiHn0dQTWlhiht0PatwFXEMmkHEEuOliwbxgUZOIcQXtHnFtgAnpkZ5uUc6FsAVJ0CLtkGnNVrOH4SIU0QgBVIRqcBRk4nJGMbNltmMCEXtufhvmQbflQb7mAXwkbs6OkeElkRADkTUXkfFh3t4YFtgL4YMU-rNhviHmAVnKUDnH7CLO8qpjzGEXnGLAHFLDLAyc7p7GEVnP7JLIlCtg1BSbnm3CsBPPwT5vUU-t6H1icWIPRl0gAKRpGl4ExYk4mHQV4R7vq5CCBLjuidDYR-HAGewSYNE8xmlP5FzNG8ZVJylLjJapY1KKnYA5aOmEbEEQEJ4UbYBt6agUa3ZFZwCeIOn5CpaenW7SD7w+lt7VK3aPHBlB6TGb5Rmki3YYkEyJm5Ex4YREjISonHExCnFSxKlDJvHRqfLE4CDfG7jamVRYHPgESSBGlCEIAASEYNGmnYDmkESZDmnFw+kIAtYaCTZ4jrp9ZBlyRJmlF5GFJtl0AdlP5dk9nQB9lWkDlgkuJPizb+D1mcFLgPi5m07Z76ZTlBa9TKlCHDHYDzmLkmkCCvTdlWm9lPnAHWk+mzaTkhkqBhnEaHiCYlHJnenxmpk9AmBZk-kpaEb-lCaulAWgWJ6IHH5ZAPmbaqlhHjjsgekc4kF0Tcl8wBlpHBEzSwmOGYWSDYXr64UmD4Wo4UaZARnO6tzjwHCEWkn3lAijHuhv5vCrF6BZZ6DIkSHPjdBYWMV4UPmExsXWFvkERoVhKzETGYWUUX7O5MkEXpnEW7ZRFmbkUqUb7qV0UMU4UQHMVimsXpnoXqlAjh7sVIE8ybkQko68VJl6AmCCX27CXKXiXj4ERSVIUW7WnyUZG6WiX6XUWUkBDSXolaWhGhWtThWmU9FGXJlmUdz7DSWFKm5kmeUTE+WtSaDRGe6SDe7LF9GZHsCKDdF0whR9G2UVEIWSGRkLxpkmFYaC7C5p5vofrJA541W0ZEkVDF4yVIFt744En55Jnd6aQJZmFVmD5QCsE7G+WT7Nn7koULXz5SnAEr4OFgE+Vb4gLRH773wBX4SkB7XCU+VX7ILRGypioP7GlIGZSCCv6XV5UmVf4fw-6yH-7JSAFPXIUQDjFNXO7bSKXu5wEXRnUoGzZsFFSYHrV0F4GxwSKEHJkIluFIkj7LXI0MG4BME1EXENTw2rXT4mDcFjC8E2XRbE3bXPViHvWg1TEkBEQyEUGwEKFKEsCeFYaJbzVaGaQ6F6F7GGGbVtXzjDjE4WG6GA0W62FyVM3JmcJiK8yyH-W82d5EkkkjXIWBGQmxWkX7WfURHjBEJuExHkKULULLFgEpGKAqkKWZHSDYk00ZYvFzYThRblDVGlGxQe2VE1HVHdz+11HZXAHXktEzE0UCAdFs3VXtSh79Fy2NFdCOXcVK0+XTFhYW30rkzLEuUOlJ0bHJVbFLVj6i36l5KFnpBnEAX3FFY3FJmrz3GPFN30Ye3lkfFVk1k1Yp3DGAnFjAmglcXbm+KG06WOE+WY0wHY0pKOEFkl5O3WXZn3F+aEm3E61ZVN7XCmJyg2gNDQB6AW7knUXf7BRmYK4Ag6o87CEmmW7UXg1hFyGnTwES0b1JmuTrq31WBt41quDRpPiVz1CbhuRPi2JWDfi-2vlIHAC+mQMCDQMb4FWJ0on9RvLwNQNt6PRdDIR8ykiYOIOxnUWHU74oldKHRmAwwbgQP2BIPUU3U35mbRQYoXLHQ0MIP0MQHn3s3CVxQMoeLNKEN0Nt5PTcWTqaDlD9ZnpZDKR6D+A8CWC0NEN3bOFcL5DP0nSeqVDsgzLCMqN0BqBsAITAQthAqENcOqZP3MNmCwAvIJR6PKOWNg2s0-UokaqSClDEocMiOqMuPlXMPshBM+Mm4GMERFTT7oIBAWPEMQGRHP29SlAcDyHwoJQhPQM6L6OaKwDlBSGo7M5L0hWhSdCAhJbFORqaA13FnOmWZXHFa2ZHjlGFLZO5NWP5NZDEBvWaT2kjYe1FaLb2bYCfCnz+CBBdBbX2AtN5OMQIRw6TMPhwCtMuMzNI6oHLWV01xTkR6NU1EJQe0JZqGmqvKXnG5TNtMrNgCAYoRo4RBiCQHTaEZuQ81BHbYkWT3G1UXHYiyN5nPLMBCzMHjDl7D3PjnjVeGTVLibL-q-Ms0XNiDBXhIDPl6V65k16enPb4ogUtVgVIvFFh2YiPhLOwv-OrNgvtUp4i7EHp6Z6fo80S383EkXnQsLM5PTMkt+RDkQAjkgvI6+YTVGa0pCUfVUXrK0o-MstEuEwAucvctTbrrp1j3z2F2i4gAb4eWnMStssaBI7jbFijnTbt7BQdWp4bWC3z0fOfYZXMuEtasITlAvhvix1PgXiGvktC4mtUvdVZ50szWqHqHnknPnZT04V3Kna1PzZcFtx13E3onoVIulAV5V55ngHPaopYv7z1PDZ4vWuLO2vYD2tySOvJB-CHigQKsg0pvQpps5usvnMksFuvjuhOsltlsK5KbluZ0hvtLis2t1vasNtFtPjlBwDrAFCluzZd2VmwSCAnkau9t-P9sOtNvFs2DIH2GaSB2Cn4kwaHNBaVCBtRPCuWs9u5t9t2tLvvhPiruKTnV9aTufHVm54-FjBVPynYCHRNPzPzvEuLuFvLtAPA2zZEjAt95LgZ50yO0ZHxuJuovITovQqwru4Lw+sNXYvdCZtLYh2fsEunsLt2ttzT4FP5ERsU1Rt3E1uSt8z4d8CcEIQ8CuuFC7vYAJRMuXEke4vlAfv4swtSv5sEe0csKKvbt81McscHvr0QvEkWa5ULLScNRQkwnvNXVdtVLc5sfbjt1E3Yc8dUcts5Yymfl1O9oabkdCG6L6INh8CXAgC71mIPAgC1hFhmRWfMCvBhARDCAjMBBJItgOjYCZMEAkDYAADkYIKQtEwX34cAykFIwYYD2AWg2AAABhqKULqMqn2pgAEOupGGl5WNmAIKuy6C9T0DYK2tgKGAropMhImk+FroELoWBCgsGO8G+CwMaCV90JmL2El9EvYNFyoEMHF2wAl8lw0afV6Ts3iYe8zS7oVRbcVaVb7uVQHlVbkjVdnWHluw8TswdQhZrcayLtSz1bO78OtykANbcUNdEjlud3np5kXpKb11F4oNgPQMN0+Il0l3CIzmzeUPVhKPsI2gQr2odsF9FBSA8e6MFxRppOUJHIEE0CwLWJ-LpIRiF6PfuMF5kJDwVs96E68IBJD4l7RIRrF2A5kHA7Z3KEuMFxSNj7BKcIzG10uG0OCP57D7HYIIBPGKN6T-GB95TzXCYnZ7T-GAzwzEzFKqz-gOzzopz4T8pPQHzw6IRu9xT94sLzcDTyF45-WKWGABL0z1L1+tc3L5z-YD90z+8P9+CCAsDxEwEIRuD5D96DD3Dwj2AEjyj+8Gjxj+Ce6Fjzj4fdgAVpb-CNbxELb4Dw76sE7+D7z275z86PDw+VHN75+hEH78F5j0hAz7z2H0hBH39wD-b+E3H2D9FHr858pEnx72n4j8j5n2ANn7nywAz8rwVuZyAH3oYyKGALMIsBZwb4P0sCAPGAAAqrcfBICiBujwjsAYTtDzBj+M57AkCNqtCkizDAB6IgBeeBA7978HCFRH-MBhB7A782ci9yjCAn-sCWcfCucrEz8iB79KaVSCDCCaixSiBaZwjVl9giAeSNAE0DLBL0SoVACYmDBqAegDwNnk1hABwY2AwgXAIpGgBTASkoA6zuEBZYyAkAYEUQCsGwgWJueoUeAPoiUBgAmcwgNuOEG74BISkxARAKUB0RAA) by setting box-sizing to border-box for every element and moving the border from the inner pre to the outer [glow] element

**Comment by gapmiss** [comment]
Excellent, that did it.

```diff
@@ -1,5 +1,8 @@
+*, *:before, *:after {
+  box-sizing: border-box;
+}
 :root {
   color-scheme: dark light;
 }
 :root {
   --main-100: #f0f9ff;
@@ -92,13 +95,15 @@

 [glow] {
   --glow-padding: 2em;
   color: var(--glow-base-color, #a2aab1);
   counter-reset: line-counter 0;
-  padding: var(--glow-padding);
+  padding: 1em var(--glow-padding);
   font-family: monospace;
   line-height: 1.7;
+  border: 1px solid var(--gray-700);
+  border-radius: 6px;
 }
 [glow] * {
   font-weight: 400;
   font-style: inherit;
   text-decoration: inherit;
@@ -161,11 +166,10 @@
   --glow-ins-color: 50, 210, 190;
   --glow-line-opacity: 0.15;
 }
 [glow] pre {
   width: 100%;
-  border: 1px solid var(--gray-700);
   border-radius: 6px;
   position: relative;
 }
 [glow] ins,
 [glow] del,
```

**Comment by tipiirai** [comment]
Great! Closing this one
