### ISSUE TITLE
In version 0.4.1, executing nue build -- production  generate a file that can be no used

### ISSUE THREAD

**Issue by hsuna** [nuejs/nue#218]
### create `app.nue`:
```
<div id="app" @name="app">
  <div>
    { title }
  </div>

  <script>
    title = "nue title"
  </script>
</div>
```

### run
```
nue build --production
```

### generate file `app.js`:
<img width="605" alt="image" src="https://github.com/nuejs/nue/assets/25148174/becf4aff-abfe-4992-972e-58e0ea81f09a">

### result:
Excessive line breaks result in script compilation failure

**Comment by tipiirai** [comment]
This is now fixed with nuejs-core 0.3.4. Thank you for reporting! This was an important fix.
