### ISSUE TITLE
In version 0.4.3, `:if` instruction failure and inconsistent display performance.

### ISSUE THREAD

**Issue by hsuna** [nuejs/nue#227]
### create `app.nue`:
```
<main @name="app">
  <ul>
    <li :for="item in items">
      <p :if="{item.value}">{ item.index }: <span>{item.value}</span></p>
    </li>
  </ul>

  <script>
    items = [
      { index: 1, value: true },
      { index: 2, value: false },
      { index: 3, value: 0 },
      { index: 4, value: 1 },
      { index: 5, value: '0' },
      { index: 6, value: '1' },
    ];
  </script>
</main>
```

### run
```
nue
```

### result:
<img width="929" alt="image" src="https://github.com/nuejs/nue/assets/25148174/bb99f644-7cc3-44ba-b42d-9b2a46f3ebaf">

- `:if` instruction failure
- `false` no display.

### desire:
<img width="630" alt="image" src="https://github.com/nuejs/nue/assets/25148174/0daa4c22-a6e0-4942-812c-6be838ea8800">

**Comment by nobkd** [comment]
Sorry for the late reply.

You just have to remove the curly braces (`{}`) from the `:if` condition to not render the `p`s when the `value` is `falsy`:

```diff
- <p :if="{item.value}">{ item.index }: <span>{item.value}</span></p>
+ <p :if="item.value">{ item.index }: <span>{item.value}</span></p>
```

---

> [!important]
> But it is true, that the `false` should be displayed as text, when there is no `:if`.

Could be related to #193 with https://github.com/nuejs/nue/commit/a3b29f5587314fb2932afb23859af837aadcb680

---

Can you tell, what you mean with `inconsistent display performance` in your title?

**Comment by hsuna** [comment]
> Sorry for the late reply.
> 
> You just have to remove the curly braces () from the condition to not render the s when the is :`{}``:if``p``value``falsy`
> 
> ```diff
> - <p :if="{item.value}">{ item.index }: <span>{item.value}</span></p>
> + <p :if="item.value">{ item.index }: <span>{item.value}</span></p>
> ```
> 
> Important
> 
> But it is true, that the should be displayed as text, when there is no .`false``:if`
> 
> Could be related to #193 with [a3b29f5](https://github.com/nuejs/nue/commit/a3b29f5587314fb2932afb23859af837aadcb680)
> 
> Can you tell, what you mean with in your title?`inconsistent display performance`

Translation software issue, please ignore it

**Comment by nobkd** [comment]
Closing in favor of #248
