### ISSUE TITLE
What you think about routing?

### ISSUE THREAD

**Issue by hozaifa4you** [nuejs/nue#24]
What you think about routing?

**Comment by tipiirai** [comment]
It's an essential feature in a single-page application. I love cute URL's! Routing & state management will be tackled with the upcoming Nue MVC project. It's based on the native `History: pushState()` method

**Comment by rehanshaikh1823** [comment]
@tipiirai what is the difference between Nue MVC and Nuekit.

**Comment by hozaifa4you** [comment]
> It's an essential feature in a single-page application. I love cute URL's! Routing & state management will be tackled with the upcoming Nue MVC project. It's based on the native `History: pushState()` method

I am waiting

**Comment by tipiirai** [comment]
Check https://nuejs.org/tools/

- Nue MVC is an alternative to things like [react-router](https://reactrouter.com/), [vue-router](https://router.vuejs.org/), [Redux](https://redux.js.org/), and [Pinia](https://pinia.vuejs.org/)
- Nuekit is an alternative to things like [Vite](https://vitejs.dev/), [Next.js](https://nextjs.org/), [Nuxt.js](https://nuxt.com/), and [Astro](https://astro.build/)

**Comment by JensRoland** [comment]
The History API works of course (strictly speaking, for SPAs, it's all we got), but corner cases can get infuriatingly tricky and pretty universally bad for accessibility.

See https://medium.com/@dvoytenko/new-web-history-api-91a1a21ff7b8 and the proposed replacement, the ([experimental](https://caniuse.com/mdn-api_navigation)) Navigation API: https://github.com/WICG/navigation-api#summary

**Comment by tipiirai** [comment]
Absolutely! When I say "based on", it means that I use it as the core, but wrap it with dynamics to make it a powerful C in  MVC.

**Comment by tipiirai** [comment]
Closing this one. Thanks guys!
