### ISSUE TITLE
When '{}' or',' in html , How to escape?

### ISSUE THREAD

**Issue by yuhengliang** [nuejs/nue#252]
`<input type="text" name="captcha" value="" placeholder="" required pattern="^\d{4,5}$" />`

When '{}' or',' in html , How to escape?

**Comment by nobkd** [comment]
I thought, something like this `pattern="{'^\d{4,5}$'}"` or this `:pattern="'^\d{4,5}$'"` would work, but it seems, the shortest match of `{}` is taken resulting in `pattern="{'^\d45$'}"` and `pattern="'^\d45$'"` respectively

So you currently have to do for example something like the following:

```vue
<div>
  <p>e.g. a layout component or area or some other scope</p>
  <input type="text" name="captcha" value="" placeholder="" required :pattern />
  <!-- or -->
  <input type="text" name="captcha" value="" placeholder="" required :pattern="patternvar" />

  <script>
    pattern = '^\d{4,5}$'
    // or
    patternvar = 'some pattern'
  </script>
</div>
```

Hope that helps, at least until there is a proper fix :)

**Comment by nobkd** [comment]
It's not the shortest match, but a match that does not contain `{` or `}`:

Related code:
https://github.com/nuejs/nue/blob/043ce76236e2e3365f4d7893ba956e2affba6161/packages/nuejs/src/expr.js#L34
https://github.com/nuejs/nue/blob/043ce76236e2e3365f4d7893ba956e2affba6161/packages/nuejs/src/expr.js#L4

---

I wouldn't expect this to ever work like you expect it to (except maybe, when `pattern` is excluded from being parsed).
It is probably the easiest to just define a variable, that contains the pattern, and use the variable.

**Comment by nobkd** [comment]
Ive thought about this again, and realized, that I thought about how to include {} in {} to allow e. G. Js code, etc, but for this, we just need an escaping + replacement part. E. g. '\}' ignored by regex and replaced after by '}'

I will check if I find a proper way for this, but if you have an idea, or on one else is interested, please just oven a pr yourself :)

**Comment by nobkd** [comment]
This behavior will probably not be changed.
