### ISSUE TITLE
Request - realworld app (demo)

### ISSUE THREAD

**Issue by salmin89** [nuejs/nue#26]
This framework lacks a realworld app demo which all the other frameworks have. Building the demo will grant you:

- something you can benchmark against other frameworks
- real comparison in bundlesizes
- all the fundamentals for your DOCS - the real world app will provide you all kinds of code examples for your docs along with a whole project-example for anyone interested in using this framework.

https://github.com/gothinkster/realworld
https://codebase.show/projects/realworld

**Comment by Axellarator** [comment]
I agree it would be useful to have more stuff to work along, but NUE has just started. It will take a while to see more.

**Comment by tipiirai** [comment]
I just pushed out Todo MVC on the website: https://nuejs.org/todomvc/ — more details coming soon. 
Later I want to create a dashboard, see #6 
I just need time :)

**Comment by salmin89** [comment]
Totally understandable. Don't rush it :) Hopefully people will help out with the realworld app.

Personally I wouldn't start the dashboard before the realworld app since dashboards are more common among enterprises, and which usually comes further down the line of adopters.

**Comment by tipiirai** [comment]
I think the real-world demo is good for showcasing Nue server components and a dashboard for reactive components.

**Comment by tipiirai** [comment]
Okay, guys. You just need to trust my promise at this point! Closing this one.
