### ISSUE TITLE
New website shaping up 🎉

### ISSUE THREAD

**Issue by tipiirai** [nuejs/nue#279]
The [summer holiday mode](https://github.com/nuejs/nue/issues/189) is still on, but I've been slowly working on the new website at https://www2.nuejs.org/

- - -
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/859ce79c-b49b-4277-a782-530686c838c6">

- - -

Here is the blog entry of the release:

https://www2.nuejs.org/blog/nue-1-beta/

Planning to push this out in a week or so

**Comment by tipiirai** [comment]
The [documentation area](https://www2.nuejs.org/docs/) is by far the biggest effort and takes weeks of writing. The vision is still mostly in my head and gets formalized as I write. 

<img width="1440" alt="image" src="https://github.com/nuejs/nue/assets/169330/b4cb4346-a7a5-4bcb-9134-1d1743d9e7b8">

**Comment by nobkd** [comment]
Added some comments/ideas:

- https://github.com/nuejs/nue/commit/fe8b031e6f6de623c7a65772abff98d1b38cca02#r142621562
- https://github.com/nuejs/nue/commit/731b48c09137844f175bc6a7ca90834e1b734fdf#r142621709
- https://github.com/nuejs/nue/commit/4f1131861d17113f347f2ea5d4fc2b243276fdca#r142622421

I might still add more. We'll see :shrug:

**Comment by tomByrer** [comment]
Looks nicer!

BTW, as someone who has a concussion ('neruo-divergent), if the animation is long-term (like in full page Hero), then slower is better.  Also **dark mode** helps a bunch.
tia

**Comment by tomByrer** [comment]
There is flashing of content/layout when switching 'tabs' (NUE | docs | blog).  You can test in incognito mode.
Linux/Brave

**Comment by nobkd** [comment]
Just so you know.
I run the website with the dev branch (at `nuejs.org` root) with `../nuekit/src/cli.js`

Edit: made a first fast read with fixing typos ([branch](https://github.com/nuejs/nue/commits/fix-docs/)):
- https://github.com/nuejs/nue/commit/752e680a73079859371a3732dd0b85df2dfe0186#commitcomment-144440439 (outdated)
- https://github.com/nuejs/nue/commit/89aaa518494962c9bdf1f83e67f7c5a7d5b2eb4e#commitcomment-144877056 (outdated)
- See #292

**Comment by tipiirai** [comment]
Done!
