### ISSUE TITLE
Simple Blog Post cannot load hero image & "Invalid date"?

### ISSUE THREAD

**Issue by gokacinlar** [nuejs/nue#307]
Hi. I was trying to build a simple blog with `bun create nue@latest` command but when I add another "blog-name.md" into the "posts" section, hero image of the post never shows up and date cannot be displayed. Its content appears but hero & date never works. Here's a preview:

![hero](https://github.com/user-attachments/assets/81a5ac8a-658a-4ac2-9d8e-08390643f81e)

The content are exactly the same (its from the example blog posts I'm using that comes with Nue) with different names, one fails to work which is the file I created.

I'm in a Windows environment, running Nue in WSL2.

**Comment by nobkd** [comment]
Hey @gokacinlar.
Do you maybe have a simple reproduction? It would probably help, to have a small repository or zip with your changes, or a short description, what exactly you modified.

Maybe you can also try to remove the generated `.dist` directory and rerun nue, to see if that helps.

**Comment by gokacinlar** [comment]
Hello @nobkd. 

> Maybe you can also try to remove the generated `.dist` directory and rerun nue, to see if that helps.

Unfortunately, this doesn't work. Here's the project I've been working on.

[project.zip](https://github.com/user-attachments/files/16570840/blog.dervisoksuzoglu.net.zip) 

I've changed nothing serious in .yaml files, just added a `{new Date().getFullYear()`} to footer.

**Comment by nobkd** [comment]
Hey, I found the issue.
One file contains CRLF line endings, the other only LF.
The file with CRLF (`\r\n`) line endings fails.
I suspect, you copied the content of the first file to the second one, and your editor saved the new file with the Windows style line endings.

I will try to create a PR, that fixes this.
For now, you'll have to ensure, your editor saves your files with LF (`\n`) line endings.

**Comment by nobkd** [comment]
Can you confirm, that if works with `lf` line endings?

**Comment by gokacinlar** [comment]
Hi @nobkd. I tested it this morning using Nano in WSL2 and now it works. 

![Screenshot 2024-08-12 2 20 49 PM](https://github.com/user-attachments/assets/8ffdc53c-e15d-4e09-83bc-ca245c6d1958)

In VSCode, you can choose whether you want to use CRLF or LF in bottom bar, this also works:

![Screenshot 2024-08-12 2 27 17 PM](https://github.com/user-attachments/assets/126b830c-eb93-400d-9074-3029633ee22a)

**Comment by nobkd** [comment]
Good to hear. Thanks for testing :)
