### ISSUE TITLE
How to handle downgrading for browsers that do not support customElements?

### ISSUE THREAD

**Issue by shuyanzi** [nuejs/nue#31]

**Comment by tipiirai** [comment]
Are you talking about the setup.js script in create-nue repository, which is the only place where custom elements are currently in use? Nue itself does not use custom elements internally atm

**Comment by JensRoland** [comment]
Is this even something worth spporting? https://caniuse.com/custom-elementsv1 has 94% support and this will only have increased by the time this could be implemented?

**Comment by tipiirai** [comment]
I also want to understand what the support actually means. See the discussion here: https://github.com/nuejs/nuejs/discussions/1#discussioncomment-7053333

**Comment by Axellarator** [comment]
I suggest to solve problems when they appear, not possible problems that never will pop up. Everybody can change his browser to the newest flavor, as easy as. But if someone likes to work with IE 4 or IE 6 or Netscape, it is fine for me.

**Comment by tipiirai** [comment]
I think "WebComponents support" is a good selling point, which makes a somewhat good reason to think about it. 

I',m closing this one, because the title does not clearly express any issue.
