### ISSUE TITLE
nue --init not working under simple-blog

### ISSUE THREAD

**Issue by tipiirai** [nuejs/nue#313]
I get the following error: 

```
Cannot find package 'nuemark' imported from /Users/tipiirai/Nue/nue/packages/examples/simple-blog/
```

The error happens at resolvePath (/Users/tipiirai/Nue/nue/packages/nuekit/src/init.js:101:45)

I guess removing the chdir hack caused this issue

**Comment by tipiirai** [comment]
The idea with the chdir hack was to import stuff under the `nue` executable, not under the working directory.

**Comment by tipiirai** [comment]
There is a new `nue create test` command, which downloads the `test.tar.gz` file instead of the 1.7M version. Good for debugging the create flow.

**Comment by tipiirai** [comment]
New, simpler installation docs: https://www2.nuejs.org/docs/installation.html

**Comment by nobkd** [comment]
> The idea with the chdir hack was to import stuff under the `nue` executable, not under the working directory.

Thanks for the explanation. I thought I tested if the command worked properly, but seems like I didn't.

I'll switch to windows for tests now, and open a PR if everything works as expected.
