### ISSUE TITLE
Animation Disrupted After Navigating Away and Returning to Page

### ISSUE THREAD

**Issue by kappalasaimohith** [nuejs/nue#327]
Hello,

I’ve encountered an issue with the animation on the documentation page at https://nuejs.org/docs/. The animation does not function as intended. This behavior disrupts the intended visual effect.

https://github.com/user-attachments/assets/c801d1d4-fa6c-4508-bd9a-0b3b06aad058

Steps to Reproduce:

1. Visit the documentation page at https://nuejs.org/docs/.
2. Click on a button in the sidebar to navigate to a different section.
3. Click on the "What is Nue?" button to return to the documentation page.
4. Observe the animation section where the animation appears to get stuck and then displays content through an unintended converging and expanding effect.

Expected Behavior:
The animation should run smoothly without delays or unusual effects.

Actual Behaviour:
After returning to the page, the animation gets stuck momentarily and then displays the content with a converging and expanding effect that does not match the intended design.

Thank you for looking into this!

**Comment by nobkd** [comment]
I'm not sure, if this can be fixed, as these are CSS animations, and typically you don't navigate that fast...

Do you maybe have an idea on how to prevent this animation issue from happening?

---

Actually, I can't even reproduce it... (using a freshly installed chromium)

**Comment by tipiirai** [comment]
I'll look into this. I think the animation itself is not ideal and can be made subtler/cooler. Thanks

**Comment by kappalasaimohith** [comment]
Hi @nobkd  and @tipiirai,
Thank you for looking into this!
I’ve noticed the issue occurs specifically in Chrome and Brave. I’ll also investigate the issue further on my end. 
Looking forward to resolving this!

**Comment by goblinfactory** [comment]
Hi Guys
I found the page animations (when they do work) to be gimmicky, i.e. distracting and unprofessional. Particularly the very short from blurred (fuzzed) to sharp. I dont believe they assist with communication or page readability and thus scores negatives from me. Just my 2 cents. (It feels forced, like it was added to the page to push the effect in from of us, to show off a feature at the expense of the reader.) 
It literally slows me down (even if it's only 1/10 of a second) from navigating quickly between link targets and back to where I was. (That combined with losing the scroll position just exacerbates the problem).
Sorry for being so harsh, didn't know a softer way to say this?

**Comment by nobkd** [comment]
I actually agree, that at least the *blur* effect is over the top.

I don't really see the view transitions currently, with Firefox as my default browser, so I can only tell about `@starting-style` effects.

(also the reason I used chromium trying to reproduce this issue)

**Comment by tipiirai** [comment]
Now the view transition effect is less distractive on the website: https://nuejs.org/

How does it work for you?

Thanks

**Comment by kappalasaimohith** [comment]
Yeah it is working fine now.
Thank you!
