### ISSUE TITLE
Glow to please support line numbers when using fence blocks 

### ISSUE THREAD

**Issue by goblinfactory** [nuejs/nue#343]
Currently if you want line numbers on your embedded `glow` code snippets, you have to use markdown as follows

this works;
```
[code numbered]
    var x = 10
    -var y = ••20••
    var z = 30
    for(i<10;i++) {
        // do •something with• all the ••numbers••
    }
```
renders as expected as follows;
<img width="476" alt="Screenshot 2024-09-09 at 16 14 17" src="https://github.com/user-attachments/assets/90eef7f3-2f6d-41b9-8d10-d9245a286ab9">

However, if you use default fenced blocks triple tick to indicate a code block, everything works except line numbers dont render.

````
```js 
    var x = 10
    -var y = ••20••
    var z = 30
    for(i<10;i++) {
        // do •something with• all the ••numbers••
    }
```
````

renders **without** the line numbers
<img width="464" alt="Screenshot 2024-09-09 at 16 17 30" src="https://github.com/user-attachments/assets/5ad84df5-c7f8-4530-8578-f56cc6bd5a24">

For larger code blocks it's helpful to have the fenced code block in your markdown use the native markdown code formatting. Otherwise it's got no formatting in the IDE and only has formatting in the rendered view.

Not sure if this is a bug, or a feature. i.e. whether it was intended for `Glow` to support line numbering of normal fenced blocks or only via custom markdown tags?

**Comment by nobkd** [comment]
If you want to switch the issue about line numbers around, you can set `numbered: true` in your `site.yaml` for global (or in your `dir.yaml` for sub-dirs) or in the front-matter, for a specific page.
:warning: But I think this is more of an accidental feature, than a planned one...

I don't think, that there currently is a way to do this natively for backtick-codeblocks (without the global / page hack) so I agree, that this would be a great addition.

**Comment by nobkd** [comment]
Should be resolved with https://github.com/nuejs/nue/commit/91feb6d4b6a53cebeb81318ef2064c53669d6cbf on dev
