### ISSUE TITLE
getting started for newbs - pre-styled components 

### ISSUE THREAD

**Issue by ghostsquad** [nuejs/nue#35]
For a newb like me, getting started with something like bootstrap or material UI makes things a lot faster. Is there a component library already or a guide on styling or converting styles from other libraries?

**Comment by tipiirai** [comment]
Not yet, unfortunately. Nue UI is on the roadmap. See: https://nuejs.org/tools/#ui

**Comment by ghostsquad** [comment]
Thanks for the response! I'll wait patiently

**Comment by tipiirai** [comment]
Good to hear! Closing this one
