### ISSUE TITLE
Adding [codetabs] to any markdown page gives runtime chrome error `Failed to resolve module`

### ISSUE THREAD

**Issue by goblinfactory** [nuejs/nue#353]
### Describe the Bug

Adding the following markdown to any `.md` page causes a runtime error, `Failed to resolve module specifier ''`

````
[codetabs "First | Second | Third" languages="js | html | css"]

    // First pane
    const foo = 'bar'
    ---

    <!-- Second pane -->
    <p>Hello, World</p>

    ---
    /* Third pane */
    p {
    background-color: yellow
    }
````

### Environment

- OS: OSX
- Package Manager: bun
- JS Runtime: bun 
- Nuekit Version: ✓ Nue 1.0.0-beta.1 • Bun 1.1.27 

### Minimal Reproduction

1. Create new blog `nue create`
1. Add a `[codetabs]` control to any markdown page, e.g. index.md
2. Browse to that page, press F12, observe error.
3. Observe no tab is rendered.

### Logs & Additional Context

```bash
mount.js:18 Uncaught (in promise) TypeError: Failed to resolve module specifier ''
    at importAll (mount.js:18:21)
    at mountAll (mount.js:26:30)
    at patch (hotreload.js:53:9)
    at async sse.onmessage (hotreload.js:84:7)
```

**Comment by nobkd** [comment]
The (unstyled) codetabs are rendered for me, but the error also exists...

![grafik](https://github.com/user-attachments/assets/7521d11f-b8e4-4bc0-b041-2aa5fb99bad4)

Not sure, what exactly happens there... (I see, that the rendered codegroup contains `is="aria-tabs"` which probably isn't "found" (I can use the tabs by clicking...))

```html
<!-- rendered codeblocks snippet in generated html file -->
<div tabs is="aria-tabs"><div role="tablist"><a role="tab" aria-selected>First</a>
<a role="tab">Second</a>
<a role="tab">Third</a></div><ul><li role="tabpanel"><pre><code language="js"><sup>// First pane</sup>
<strong>const</strong> <b>foo</b> <i>=</i> <em>&apos;bar&apos;</em></code></pre></li>
<li role="tabpanel" hidden="hidden"><pre><code language="html"><sup>&lt;!-- Second pane --&gt;</sup>
<i>&lt;</i><strong>p</strong><i>&gt;</i>Hello<i>,</i> World<i>&lt;</i><i>/</i><strong>p</strong><i>&gt;</i></code></pre></li>
<li role="tabpanel" hidden="hidden"><pre><code language="css"><sup>/* Third pane */</sup>
p <i>{</i>
    <b>background-color</b><i>:</i> yellow
<i>}</i></code></pre></li></ul></div>
```

Can you check, if your rendered html includes the rendered layout+client/hybrid component?

**Comment by tipiirai** [comment]
I don't get the "Failed to resolve module specifier '' error. The tabs are working for me with the above code

**Comment by tipiirai** [comment]
Sorry... I am getting the error now. I was looking for it from the wrong place :) Fixing..
