### ISSUE TITLE
Access to current Nuejs version as a system variable 

### ISSUE THREAD

**Issue by goblinfactory** [nuejs/nue#356]
###  Provide build time access to  current nuejs version, and runner (bun, vs node) as default system variables, merged with site settings, so that they can optionally be included in the footer with a link back to nue website.

This would help with nuejs branding for the test review sites I'm building. 

Since i'm currently using a devops pipeline on cloudflare to build my sites and deploy on code check in, that will be super helpful to confirm what version bun installs. 

My devops pipeline is OH SO COMPLEX; it's literally this one line ; `bun install && bunx nue build --production` together with this `package.json`  (needed for cloudflare)
```json
{
  "devDependencies": {
    "nuekit": "latest",
    "wrangler": "^3.50.0"
  }   
}
```
Since I'm always using latest; the version of nue that will be used, will have been the version that was fetched and installed at the time of the last code commit.  Having access to the specific nue version as a system variable alongside (merged) with all the site.yaml data would be very helpful. 
 
### Solution you'd like

To be able to access these as global variables, for example;

```html
<div @name="footer">
  <span class='ver'> {version}</span>
</div>
```
would generate the following in my hypothetical "footer"
```
Nue 1.0.0-beta.2 • Bun 1.1.27 
```
I considered splitting these, to have nue version and host/runner version separately, but sticking to the "less is more" mantra, I can't see any reason why that as a single string should be sufficient.

### Alternatives you've considered

Environment variables; but this would mean a much longer devops pipeline script, but is problematic on Cloudflare where you don't  have access to process.environment due the sandbox.  Even if I did, the amount of work to get this, seems overkill if it can easily be made available.

**Comment by nobkd** [comment]
This was actually possible before, using `nuekit_version`, but seems to have been broken somewhere along the way. Thanks for accidentally finding a bug :D

**Comment by goblinfactory** [comment]
@nobkd I think a test should perhaps accompany the fix?
:D
