### ISSUE TITLE
`<slot for="content" />` doesn't work

### ISSUE THREAD

**Issue by nobkd** [nuejs/nue#369]
### Describe the Bug

`<slot for="content" />` is ignored and does not get replaced with the rendered md.

### Environment

- OS: Fedora Linux 40
- Nue 1.0.0-beta.2 • Bun 1.1.27
 
### Minimal Reproduction

`layout.html`
```html
<main>
  <slot for="content" />
</main>
```

`index.md`
```md
# title
```

---

result:

```html
<main></main>
```

expected:

```html
<main>
  <h1>title</h1>
</main>
```

**Comment by tipiirai** [comment]
Probably works currently with `<slot for="layout.article" />`. 

Thinking of changing the name to `<slot for="layout.content" />` and updating the docs

**Comment by nobkd** [comment]
Closing, as docs are fixed on dev
