### ISSUE TITLE
Docs sidebar orientation

### ISSUE THREAD

**Issue by nobkd** [nuejs/nue#398]
On the new (dev branch) docs, the function `setSelected` (I think) deselects the current left sidebar element (which page I am on) when I start to scroll (or switch from another page and it scrolls to the top), as it selects the element in the right heading/section sidebar.

[issue.webm](https://github.com/user-attachments/assets/23a62e24-c27d-497a-a057-394e70d8839b)

**Comment by tipiirai** [comment]
This should be fixed on the new website: 

https://nuejs.org/docs/

**Comment by nobkd** [comment]
Thanks
