### ISSUE TITLE
'JXS' in README.md seems to be a typo

### ISSUE THREAD

**Issue by PoleStarInTheSky** [nuejs/nue#4]
> While React and JXS claim to be "Just JavaScript", Nue can be thought of as "Just HTML". Nue is perfect for [UX developers](https://css-tricks.com/the-great-divide/) focusing on interaction design, accessibility, and user experience.
 
It seems that JSX should be here.

That's a pr related to this issue:https://github.com/nuejs/nuejs/pull/3

**Comment by tipiirai** [comment]
Thank you @PoleStarInTheSky ! Merged
