### ISSUE TITLE
Good Job, BUT.......

### ISSUE THREAD

**Issue by theajack** [nuejs/nue#40]
This is also a good project：[Alins](https://alinsjs.github.io/docs) 😄

**Comment by tipiirai** [comment]
Looks good and minimalistic! Good job there. I see many similarities, but also many differences. Syntax wise I think the biggest difference is that Nue attempts to be a good option for the "old school" UX developers with preference for semantic HTML and lightweight JavaScript, which I think is best implemented with a class-based- approach. The grand vision (https://nuejs.org/tools) is also a major separator. Anyway, glad to see minimalistic options challenging the React-dominant developer community.

**Comment by tipiirai** [comment]
Did I answer your "question"? ie: how to close this issue?
