### ISSUE TITLE
nue create fails on Windows

### ISSUE THREAD

**Issue by appurist** [nuejs/nue#403]
### Describe the Bug
An attempt to run `nue create simple-blog` produces an error on Windows.

### Environment
- OS: Windows 11
- Nuekit version & JS runtime: ✓ Nue 0.5.3 • Bun 1.1.34

### Minimal Reproduction
- run `nue create simple-blog`  on Windows 11

### Logs & Additional Context
In my case, I get the following output:
```
PS C:\dev\nue> nue create simple-blog

✓ Nue 0.5.3 • Bun 1.1.34
✓ Initialize ./.dist/dev: •••••ENOENT: No such file or directory
   errno: -2
 syscall: "copyfile"
   path: "C:/Users/paul/AppData/Local/pnpm/global/5/.pnpm/nue-glow@0.2.1/node_modules/nue-glow/minified/glow.css"
```

Running it a second time produces this output:
```
PS C:\dev\nue> nue create simple-blog

✓ Nue 0.5.3 • Bun 1.1.34
✓ Building site to: ./.dist/dev

Time taken: 1ms
```
With a new project name:
```
PS C:\dev\nue> nue create simple-blog2

✓ Nue 0.5.3 • Bun 1.1.34
✓ Building site to: ./.dist/dev

Time taken: 1ms
```
Running it under CMD.EXE rather than PowerShell produces the same output (does not seem to be PS-specific).

If I `ls` the current folder, it only contains a `.dist` folder with `.dist/dev/@nue` folders with:
```
PS C:\dev\nue> ls .dist/dev/@nue

    Directory: C:\dev\nue\.dist\dev\@nue

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2024-11-15  1:58 PM              0 .043
-a---          2024-11-15  1:58 PM           1703 app-router.js
-a---          2024-11-15  1:58 PM           2345 mount.js
-a---          2024-11-15  1:58 PM          10870 nue.js
-a---          2024-11-15  1:58 PM            676 nuemark.js
-a---          2024-11-15  1:58 PM           3368 page-router.js
```

**Comment by appurist** [comment]
FYI, I successfully ran the same command from a Mac zsh prompt. No troubles there.

I can assist further if you don't have access to a Windows machine.

**Comment by nobkd** [comment]
Hey, can you upgrade your `nuekit` version to `1.0.0-RC.1` and try creating the `simple-blog` starter again, please?
Quite a lot changed, and some stuff works different from a few versions ago. The starter also targets the latest release.

PS:
You can't use `nue create simple-blog2`. The **name of the starter** is `simple-blog`.
If you want to *create* the template to a different directory, you can provide `--root <dir>` or `-r <dir>`.
E.g. `nue create simple-blog -r my-custom-dir`

**Comment by appurist** [comment]
Thanks for the clarification of the commandline arguments. I thought it was a generic blog template (the only one) and the argument was my folder/project name but I see now it's actually both. More templates coming?

In terms of the RC, something is wrong. I installed both `bun` and `nuekit` on Nov 15th (1pm Eastern) after reading the RC blog post. It should have been the RC.

I just tried running `nue --version` again to confirm:
```
> nue --version
✓ Nue 0.5.3 • Bun 1.1.34
```
And then I ran `bun install nuekit --global` again to reinstall and it says `installed nuekit@0.5.2...` but then reports 0.5.3 still.
```
PS C:\dev\nue> bun install nuekit --global
bun add v1.1.34 (5e5e7c60)

installed nuekit@0.5.2 with binaries:
 - nue

[151.00ms] done

> nue --version
✓ Nue 0.5.3 • Bun 1.1.34
```
Perhaps there's a windows-specific problem installing nuekit, or a problem if an old one was installed previously. I don't normally use bun so it may be bun-specific too, as its support for Windows is questionable.

I will try to uninstall nuekit and then reinstall. It may also be a path-not-updated problem so I'll check on that.

**Comment by appurist** [comment]
ok one thing resolved, one remaining.

```
PS C:\dev\nue> nue --version
✓ Nue 0.5.3 • Bun 1.1.34
PS C:\dev\nue> bun uninstall nuekit --global
bun remove v1.1.34 (5e5e7c60)

- nuekit
1 package removed [16.00ms]
PS C:\dev\nue> bun install nuekit --global
bun add v1.1.34 (5e5e7c60)

installed nuekit@1.0.0-RC.1 with binaries:
 - nue

8 packages installed [1236.00ms]
PS C:\dev\nue> nue --version
✓ Nue 0.5.3 • Bun 1.1.34
PS C:\dev\nue>
```
After uninstalling and reinstalling nuekit globally, the installation reported the correct RC version. However, running it again did not. I'll dig into that next.

**Comment by appurist** [comment]
Okay, resolved.  Apparently at some point I had used `npm` to install nuekit and it was finding that first. I removed it and installed it again and it's good now, and `nue create simple-blog` worked like a charm. Very smooth (and fast)!

Thanks!

**Comment by nobkd** [comment]
Great to hear that.
I actually had almost the same problem, when I tried reproducing your issue on my windows vm 😅

(But on this I didn't connect the dots to this issue, cause it was a local linked version, where I tested some stuff with nue+node+windows)

PS:
I think there are more starters planned, but probably not right now.

Actually, I think you can leave out `simple-blog` on the create command, as it is the default. 
Like: `nue create` or `nue create -r custom-dir`
But I'm not too sure and would have to test that myself :)
