### ISSUE TITLE
I think you don't  need jest 🥸

### ISSUE THREAD

**Issue by Valexr** [nuejs/nue#406]
Jest very complicated & heavy...
Try light & simple [UVU](https://github.com/lukeed/uvu) test runner. 

I think it's enough for Nue philosophy 🤓 & I can help make simple changes for all tests...

**Comment by nobkd** [comment]
We have jest only as secondary test runner.
We primarily use Bun as test runner, and just use jest to test Node compatibility.
Using jest allows using the same test syntax, and it has feature parity.

I can check out uvu, if it has the available features, and some compatibility layer for syntax, but I don't know if it fits our use case. :)
(of course would be good if we could have a smaller data and resource footprint on that) 

I think I'll try taking a closer look sometime next week.

**Comment by Valexr** [comment]
Oh didn't consider that bun has a test runner...🤓ok, tx for feedback

**Comment by nobkd** [comment]
I don't think, it is worth the effort implementing a layer in between, to use the same test syntax.
