### ISSUE TITLE
How I can control url generation?

### ISSUE THREAD

**Issue by Valexr** [nuejs/nue#411]
I publish `.dist/prod` to GitHub [Pages](https://valexr.github.io/simple-blog/) & get issue with relative links in images & anchors...

![Screenshot 2024-11-19 at 21 45 53](https://github.com/user-attachments/assets/a298bb49-896c-47b0-8d08-a0f43b01ff11)

**Comment by nobkd** [comment]
You need to add the `base` key to your yaml file containing the directory path where the files are on the server.
In your case this would be `base: /simple-blog`.

You can automate this for the server using e.g. A script which uses an env yaml file.
Example:
Create `prod.yaml`
Add line `base: /simple-blog`
Add script to `package.json` or a script file: `nue build -p -e prod.yaml`. This merges  `prod.yaml` keys on `site.yaml` and overrides duplicate keys with values from env file

Maybe [my repo](https://github.com/nobkd/nue-editor) (just a project idea at the moment) (might have a broken icon atm, idk) gives more insight, how you could do publishing with gh workflows, if you wanted to. (And if you don't want to upload your `.dist/prod` directory)

Good luck.

**Comment by Valexr** [comment]
O thx @nobkd 👍🏻
Nue-editor… interesting! How it will be work? MD editor?

**Comment by nobkd** [comment]
Yeah, mainly.
Sadly I'll be a bit low on time for longer..., so nue's core libraries are more important to me.

**Comment by nobkd** [comment]
I'll close this as done. If you experience some issue with it, please reopen or just comment :)
