### ISSUE TITLE
The comparison of code lines is funny🤡

### ISSUE THREAD

**Issue by boiboif** [nuejs/nue#45]
🤡🤡🤡🤡🤡🤡🤡🤡

**Comment by wangnan0916** [comment]
Who wants to write so much code to solve the same thing?

**Comment by wangnan0916** [comment]
The main thing about coding is whether your thinking and plan is good. With a good thought and plan, programming experience is also important, like writing less code.

**Comment by Sorryhx** [comment]
> Who wants to write so much code to solve the same thing?

writing code is best  without any framework and packages 😂

**Comment by tipiirai** [comment]
🤡 What is the exact issue and how to solve it? Thanks

**Comment by tipiirai** [comment]
Closing this. Thanks
