### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'render')

### ISSUE THREAD

**Issue by hooliy** [nuejs/nue#46]
error info : 
 return comps[0].render(data, comps)
                  ^
TypeError: Cannot read properties of undefined (reading 'render')

// import rendering method
import { renderFile } from 'nue'

// render the component
const html = renderFile('media-object.nue', {
  title: 'Media object',
  desc: 'One object to rule them all',
  img: 'img/art.jpg',
  type: 'banner',
})

// output
console.info(html)

**Comment by tipiirai** [comment]
Do you have the `media-object.nue` in the current working directory?

**Comment by hooliy** [comment]
> directory

Yes, the directory file is correct.

**Comment by tipiirai** [comment]
Can you paste the stack trace? Are you possibly on Windows, which is not tested at all currently?

**Comment by hooliy** [comment]
I created a simple repository to reproduce this issue, which exists on both Mac and Windows. It could also be a problem with my usage. I mainly want to use it for generating code based on NodeJS. @tipiirai 

[https://github.com/hooliy/nuejs-example.git](https://github.com/hooliy/nuejs-example.git)

**Comment by gucovip** [comment]
@tipiirai @hooliy This issue was fixed by #18 .
This version (0.1.1) does not include this fix.

**Comment by hooliy** [comment]
3Q, the issue has indeed been fixed.
