### ISSUE TITLE
Can't it be an alternative to angular?

### ISSUE THREAD

**Issue by HCenggel** [nuejs/nue#55]
Can't it be an alternative to angular?

**Comment by tipiirai** [comment]
It surely can. However, In the docs I wanted to list the options that a new developer would pick today. I think Angular is not on that list unless I'm wrong.

**Comment by HCenggel** [comment]
> It surely can. However, In the docs I wanted to list the options that a new developer would pick today. I think Angular is not on that list unless I'm wrong.

I suggest writing angular

**Comment by HCenggel** [comment]
Because I want to see what the difference will be between these two frameworks

**Comment by tipiirai** [comment]
> I suggest writing angular

I'm thinking of writing a more detailed comparison articles from Svelte, React, and Vue first. Then maybe HTMX, since it's been asked. Is Angular still a choice for new projects? Any stats?

**Comment by HCenggel** [comment]
> > I suggest writing angular
> 
> I'm thinking of writing a more detailed comparison articles from Svelte, React, and Vue first. Then maybe HTMX, since it's been asked. Is Angular still a choice for new projects? Any stats?

I have many angular projects, so I want to know the difference between these two frameworks.
