### ISSUE TITLE
Fix needed: Starting a new create-nue without errors 

### ISSUE THREAD

**Issue by Axellarator** [nuejs/nue#58]
### Solution first: 
> In package.json do this changes:
```
  "scripts": {
    "start":   "nue create  || (./scripts/cli.js minify --prod && ./scripts/cli.js render && ./scripts/cli.js compile && ./scripts/cli.js server)",
    "minify":  "nue minify  || ./scripts/cli.js minify --prod",
    "render":  "nue render  || ./scripts/cli.js render",
    "compile": "nue compile || ./scripts/cli.js compile",
    "serve":   "nue server  || ./scripts/cli.js server"
```
Remove the cd www part!

### Modify server.js in scripts
```
    const path = join('www/', url)
```
All scripts above will run
---

Starting a new create-nue and get that. missing scripts/cli.js is in scripts dir.

`
> create-nue@0.1.3 serve
> cd www && nue server || ./scripts/cli.js server

sh: line 1: nue: command not found
sh: line 1: ./scripts/cli.js: No such file or directory
`
Starting works in the following case, but after opening localhost:8080 it's over. Website crash.
`
> create-nue@0.1.3 start
> nue create || (./scripts/cli.js minify --prod && ./scripts/cli.js render && ./scripts/cli.js compile && ./scripts/cli.js server)

sh: line 1: nue: command not found
No builder found (esbuild or Bun) www/nue.js is not minified
wrote www/index.html
compiled www/islands.js
Node HTTP server at http://127.0.0.1:8080/
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'index.html'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'index.html'
}

Node.js v20.7.0
`

**Comment by wangh09** [comment]
Great, that solved my problem. BTW, why is there a 'nue: command not found' error? While the web renders correctly.

**Comment by tipiirai** [comment]
This is fixed. Please pull the latest according to the installation docs: https://github.com/nuejs/create-nue#installation

Thanks guys!
