### ISSUE TITLE
Support inline svg elements

### ISSUE THREAD

**Issue by nurges** [nuejs/nue#60]
Inline svg elements in .nue files get replaced with `<nue-island>`

``` html
<svg style="display:none;>
  <symbol id="collapse" viewBox="0 0 16 16">
    <polygon points="11.62 3.81 7.43 8 11.62 12.19 10.09 13.71 4.38 8 10.09 2.29 11.62 3.81" />
  </symbol>
</svg>
```

in a .nue file is compiled to

``` html
<svg style="display:none;>
  <nue-island id="collapse" viewBox="0 0 16 16">
    <nue-island points="11.62 3.81 7.43 8 11.62 12.19 10.09 13.71 4.38 8 10.09 2.29 11.62 3.81" />
  </nue-island>
</svg>
```

We should add the svg elements to the standard element list.
[SVG container elements](https://svgwg.org/svg2-draft/struct.html#TermContainerElement)
[SVG graphics elements](https://svgwg.org/svg2-draft/struct.html#TermGraphicsElement)

**Comment by tipiirai** [comment]
Good call. Will fix. Thanks!
