### ISSUE TITLE
Suggestion: add https://nuejs.org/ link to GitHub repo description

### ISSUE THREAD

**Issue by JensRoland** [nuejs/nue#61]
When browsing a cool repo, especially one that has a more mainstream dev appeal (frameworks/libraries, not protocols/drivers) I personally like to browse the public-facing web site first, to get a feel for the selling points, the docs, the official guides.

The link is usually found either at the top of the README or in the GitHub description field:

![Screenshot 2023-09-28 at 23 09 57](https://github.com/nuejs/nuejs/assets/210009/1b57d208-21d4-4e26-9ba9-4afac09bcc31)

With Nue JS I was surprised to find that the official project web site is not linked from the repo -- which is a shame since the web site is really nice and communicates what Nue JS aims to do in a good way.

So maybe add the link? :-)

**Comment by tipiirai** [comment]
Oh! I have totally missed this one. It's now there. Thank you! This was important
