### ISSUE TITLE
Maybe add a prettier config here so devs can contribute better?

### ISSUE THREAD

**Issue by theVedanta** [nuejs/nue#7]

**Comment by angel-git** [comment]
Also maybe consider using some eslint or something similar to fix these kind of warnings for you:
![image](https://github.com/nuejs/nuejs/assets/1565058/5abb0ae7-eff2-468a-8d4f-ab5d5eddb951)

**Comment by theVedanta** [comment]
I would also suggest having bun.lockb in the gitignore. Bun is mentioned quite a bit in the docs...

**Comment by tipiirai** [comment]
Can you help with the prettier config? At least the base work that I can tweak if needed. I'm not familiar with prettier and I'm using Sublime which does not give me those warnings. Please note that the loose equality comparison `==` is there [in purpose](https://github.com/nuejs/nuejs/blob/master/CONTRIBUTING.md#faq)

**Comment by tipiirai** [comment]
Added bun.lockdb to `dev` branch

**Comment by theVedanta** [comment]
> Can you help with the prettier config? At least the base work that I can tweak if needed. I'm not familiar with prettier and I'm using Sublime which does not give me those warnings. Please note that the loose equality comparison `==` is there [in purpose](https://github.com/nuejs/nuejs/blob/master/CONTRIBUTING.md#faq)

Sure. And yes I understand you are maintaining simplicity by using "=="

**Comment by tipiirai** [comment]
I'm using it because == is a different operator than ===. It's all about the context. For example, if I need to know whether something is not present then == is the correct operator.

**Comment by tipiirai** [comment]
Also negation operator: `!thing` is equivalent to ==
