### ISSUE TITLE
'.' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by IsmailYaman** [nuejs/nue#71]
After following the installation process, I get the following error after  `npm run start`:
```
npm run start

> create-nue@0.1.4 start
> ./scripts/cli.js start

'.' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by JensRoland** [comment]
I think this may be caused by the `./scripts/cli.js` path -- on Windows it would expect `.\scripts\cli.js`.

**Comment by ericchase** [comment]
it looks like the author was trying to take advantage of shebangs, which work for unix platforms. this doesn't work on windows, so each script needs "node" in front of it.

```
  "scripts": {
    "start": "node ./scripts/cli.js start",
    "minify": "node ./scripts/cli.js minify",
    "render": "node ./scripts/cli.js render",
    "compile": "node ./scripts/cli.js compile",
    "serve": "node ./scripts/cli.js serve"
  },
```
