### ISSUE TITLE
error: '.' Not an internal or external command, nor a runnable program or batch file.

### ISSUE THREAD

**Issue by chnkarl** [nuejs/nue#72]
i'm window11, my steps:

1. git clone create-nue

2. cd create-nue

3. npm i 

4. npm run start

then, get that error

**Comment by nobkd** [comment]
See https://github.com/nuejs/nuejs/issues/71#issuecomment-1745847892

**Comment by chnkarl** [comment]
i wil try again later, appreciate your apply



---Original---
From: "Tero ***@***.***&gt;
Date: Wed, Oct 4, 2023 13:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nuejs/nuejs] error: '.' Not an internal or external command, nora runnable program or batch file. (Issue #72)




 
Closed #72 as completed via nuejs/create-nue#23.
