### ISSUE TITLE
"for in" and "for of" should be distinguished in expr.js file

### ISSUE THREAD

**Issue by YmBIgo** [nuejs/nue#73]
In expr.js's `parseFor` function, codes do not distinguish `for in` and `for of` [here](https://github.com/nuejs/nuejs/blob/a5c844494852cdbe3282fdc588ca81742f39b56e/ssr/expr.js#L95) . However, `for in` and `for of` should be distinguished because `for in` only takes `index i` in first argument if array and only takes `key` in first argument if object. See command prompt results below.

[ for in Object ] ↓
<img width="565" alt="スクリーンショット 2023-10-04 19 40 43" src="https://github.com/nuejs/nuejs/assets/8908109/d6ab9270-9240-4647-8609-3c279ef07aff">

[ for in Array ] ↓
<img width="570" alt="スクリーンショット 2023-10-04 19 43 32" src="https://github.com/nuejs/nuejs/assets/8908109/b96db13f-bc25-41a8-abd7-ca5dd2ce75f3">

[ for in Object.entry(object) ] ↓
<img width="571" alt="スクリーンショット 2023-10-04 20 26 05" src="https://github.com/nuejs/nuejs/assets/8908109/cc2c03d6-fe6c-4efb-8ceb-1bc9b82c3280">

---

And here is a point. If array I can come up with how to fix it. See codes below.

```javascript
export function parseFor(str) {
  let [prefix, forType, expr ] = str.trim().split(/\s+(in|of)\s+/)
  prefix = prefix.replace('(', '').replace(')', '').trim()
  expr = setContextTo(expr)

  if (forType=== "of") {
    // "for of" syntax
    // Object.entries()
    if (prefix[0] == '[') {
      const keys = parseKeys(prefix)
      return [ keys.slice(0, 2), expr, keys[2] || '$index', true ]

    // Object deconstruction
    } else if (prefix[0] == '{') {
      const { keys, index } = parseObjectKeys(prefix)
      return [ keys, expr, index || '$index' ]

    // Normal loop variable
    } else {
      const [ key, index='$index' ] = prefix.split(/\s?,\s?/)
      return [ key, expr, index ]
    }
  } else {
    // "for in" syntax only takes first i if array
    if (prefix[0] === '[') {
      const keys = parseKeys(prefix)
      return [undefined, expr, keys[0]] // Can I pass undefined in keys here?
    } else if (prefix[0] === '{' ) {
      return [ undefined, expr, "$index" ] // Can I pass undefined in keys here?
      // or throw error since only undefined to be returned in for loop
    } else {
      const [index, _rest] = prefix.split(/\s?,\s?/)
      return [undefined, expr, index] // Can I pass undefined in keys here?
    }
  }
}
```
But for Object loop I cannot discover any idea to implement, since There are no way to recognize whether `expr` is a object or a array.
Therefore I want to implement `for in` for array and leave `for in` for object for further works.

Any questions, rebuts or suggestions are welcome!

Thank you for reading the issue.

[ Edit ]
I have read the tests codes and docs, and I realize that you have used `for in` syntax for many places. So if you think fixing these `for in` that have written is troublesome, it may not be something you have to do.

**Comment by tipiirai** [comment]
I took this directly from [Vue's documentation](https://vuejs.org/guide/essentials/list.html#v-for). I believe there is no distinction between `in` and `of`, or do you know? I'm actually thinking of *removing* the "of"- option and only support "in". Less code, ground for issues, confusion, documentation, support, etc.. Thoughts?

**Comment by YmBIgo** [comment]
Oh. I usually use React, so I don't know that. Thanks.
