### ISSUE TITLE
Text expressions can't have the dash charachter (-) in their name or value returns NaN

### ISSUE THREAD

**Issue by korabdoroci** [nuejs/nue#78]
I don't know if this is intended behaviour or not, but I thought I'd let you know.

I created this project using create-nue with node.

**This code Returns ( Text: NaN ) in the button element:**

components.nue:
```
<!-- test-button -->
<button @name="test-button">
  text: {button-text}
</button>
```

layout.nue:
```
<html>
  <meta charset="utf-8">
  <test-button button-text="it worked" />
  <script type="module" src="setup.js"></script>
</html>
```

**While this code returns ( text: it worked ) as expected:**

components.nue:
```
<!-- test-button -->
<button @name="test-button">
  text: {buttontext}
</button>
```

layout.nue:
```
<html>
  <meta charset="utf-8">
  <test-button buttontext="it worked" />
  <script type="module" src="setup.js"></script>
</html>
```

**Comment by gucovip** [comment]
The usage of `{button-text}` makes it impossible to tell if it is an expression `button minus text` or a variable `button-text`.
Is there a good way to tell the difference? @Korab-Doroci @tipiirai

**Comment by tipiirai** [comment]
This is expected behaviour. Think expressions like function bodies that must return a value. `{button-text}` translates to:

``` js
function(self) {
  return self.button - self.text
}
```
Where `self` is the component instance. `buttontext` is a variable name and works in your case.

**Comment by korabdoroci** [comment]
Thank you for clarifying!
