### ISSUE TITLE
git clone git@github.com:nuejs/create-nue.git

### ISSUE THREAD

**Issue by Axellarator** [nuejs/nue#8]
Tried `git clone git@github.com:nuejs/create-nue.git`
Get `Cloning into 'create-nue'...`
      `git@github.com: Permission denied (publickey).`
      `fatal: Could not read from remote repository.`

      `Please make sure you have the correct access rights`
      `and the repository exists.`

**Comment by JLarky** [comment]
I've had this issue before :) you need http link instead of git/ssh link

**Comment by tipiirai** [comment]
oh. okay. I'll fix the docs. thanks guys!

**Comment by tipiirai** [comment]
pushed the fix to this repo and the website
