### ISSUE TITLE
没有热更新吗？这样会有开发效率吗？

### ISSUE THREAD

**Issue by Mluocheng** [nuejs/nue#84]

**Comment by beMySun** [comment]
哈哈
作者： 别催，在做了。

**Comment by ShiMeiWo** [comment]
@Mluocheng
You are probably requesting about HMR, but @tipiirai is Finnish, so saying it in Chinese would not be understood.
你可能是在问 HMR，但 @tipiirai 是芬兰人，用中文说他可能听不懂。

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!

**Comment by tipiirai** [comment]
Please post the issue here directly and in English or Finnish :) Thanks!
