### ISSUE TITLE
the server can reload automatically?

### ISSUE THREAD

**Issue by hksk** [nuejs/nue#9]
how I can run the server in development mode? I just need to stop/start the run script to see my changes.

**Comment by tipiirai** [comment]
There is no such mode in this repository since this will be part of the upcoming Nuekit project. For now you'd need to build it yourself using [chokidar](https://github.com/paulmillr/chokidar) or similar

**Comment by Axellarator** [comment]
see in discussions: Running a NUE server loop

**Comment by tipiirai** [comment]
Closing this. Auto-reloading is part of the upcoming [Nuekit](https://nuejs.org/tools/#nuekit) project.
