### ISSUE TITLE
Will a CLI be coded to create Nue.js projects from the terminal?

### ISSUE THREAD

**Issue by ghost** [nuejs/nue#90]
Instead of cloning the 'create-nue' repository, such a CLI can make the project easier to set up and more customizable.

**Comment by nobkd** [comment]
Not sure, as there isn't much information about what's going to change, but this issue might be the best place to look around. See nuejs/create-nue#27.
There might come something like `npm create nue`. See https://github.com/nuejs/www/pull/25#issuecomment-1752512160.

**Comment by tipiirai** [comment]
There will be one. Thinking of integrating the planned "Nuekit" to the Nue JS repository because they are so much interlinked. This likely happens next week even.

**Comment by tipiirai** [comment]
This is now implemented. See: https://nuejs.org/docs/reference/command-line-interface.html
