### ISSUE TITLE
Switch to more web-component compatible island syntax

### ISSUE THREAD

**Issue by tipiirai** [nuejs/nue#99]
Instead of using this placeholder syntax for client-side components:

``` HTML
<nue-island island="my-component"></nue-island>
```

I'm proposing this:

``` HTML
<my-component engine="nue"></my-component>
```

Which looks more like a web-component. There needs to be some specifier, that the component is powered by Nue. Proposing "engine". Could be "data-engine" as well. Any suggestions / thoughts?

**Comment by ShiMeiWo** [comment]
If I had to come up with attributes names other than "engine", they would be:

- def
- from
- beborn
- madeof
- generator

...What awkward names! I think "engine" is more better.

**Comment by ShiMeiWo** [comment]
BTW, I want to know that if the implementation is done, will the rendered DOMs change from

```vue
<div island="my-component" :bind="item" />
```

to

```vue
<my-component :bind="item" />
```

like other "frontend framworks"?

And if so, the selector in CSS should be `my-component {...} ` instead of `[island="my-component"] {...} ` ?

**Comment by ShiMeiWo** [comment]
@tipiirai Do you plan to adopt this syntax in the upcoming NueKit release?

**Comment by tipiirai** [comment]
This didn't made it to the release yet. This is a low-priority issue, because there is no apparent problem that this solves. Or is there?

**Comment by tipiirai** [comment]
This is now implemented in a fully standards-based manner without any self-invented attribute names. For example, a custom element like `<my-element>` is now rendered as:

``` html
<div is="my-element"></div>
```

The `is`- attribute is a [standard, global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/is) and when this is found on a document Nue works as follows:

1. If there is a custom HTML element defined with that name, the node is renreded as defined by the component
2. Otherwise the node is mounted with a reactive Nue component, if one is defined

This brings substantial clarity for the whole division between web components and Nue/React/Svelte ecosystem. The standard web components are good for defining simple interactions and the reactive libraries are good for more complex interactivity. 

All auto-mounting and hot-reloading features are now implemented to support this new syntax. 

This is obviously a backwards- incompatible change, but the major version number won't change until we switch production with 1.0 version. Before that, in beta stage, we are only increasing the second version number. Mark would say "move fast, break things".

**Comment by nobkd** [comment]
Closing this, as the main concern has been resolved and released. Feel free to comment here or open a new issue if there is something left open.
